
const proyectos = {
  1: "<b>PROHIBICIÓN DE TRAPITOS.</b>Ya presentamos un proyecto de ley para convertir en contravención a la actividad de los trapitos/ cuidadoches. Los trapitos: prohibidos y presos. MODIFICASE LA LEY N° 1472, CÓDIGO CONTRAVENCIONAL DE LA CIUDAD* Expediente: <b>3704-D-2024</b> Presentado: <b>6/2/2025</b> ",
  2: "<b>2. TRANSPORTE COMO SERVICIO PÚBLICO ESENCIAL</b> Presenté un proyecto para que el transporte urbano sea declarado como servicio público esencial. ¿Qué quiere decir eso? Que ningún paro o protesta puede impedir que se provea el servicio. Es decir, vas a tener transporte siempre, aunque sea con menor frecuencia. Definir a un servicio público como esencial ayuda a que podamos armonizar de mejor manera los derechos y se logra impedir que haya adhesiones forzosas al paro. Si no se corta al transporte, muchas personas van a ir a trabajar igual si no adhieren al paro. Más libertad, más orden, mejor convivencia. Presentado el <strong>30/10/2024</strong> Expediente <strong>3157-D-2024</strong>  ",
  3: "<b>3. EDUCACIÓN COMO SERVICIO PÚBLICO ESENCIAL</b> Presenté un proyecto para que la educación sea declarada como servicio público esencial. ¿Qué quiere decir eso? Que ningún paro va a impedir que tus hijos estén en la escuela. Muchas veces las medidas de fuerza afectan a la cantidad de días de clase efectivos y eso disminuye el rendimiento escolar de nuestros hijos, condicionando su futuro y el de nuestro país.  Además, cuando un hijo se queda sin ir a clases, muchas veces sus padres tienen que perder el día de trabajo o incurrir en mayores gastos. Por eso presenté este proyecto para evitar que usen a nuestros hijos de rehenes. Presentado el <b>6/3/2025</b> Expediente <b>325-D-2025</b> ",
  4: "<b>4. PROVISIÓN DE COMBUSTIBLE COMO SERVICIO PÚBLICO ESENCIAL</b> Presenté un proyecto para que toda la cadena de suministro de combustible sea declarada un servicio público esencial para que los paros no impidan que puedas cargar combustible. Junto con los dos proyectos anteriores, constituyen un paquete que busca evitar que el paro de actividades que condicionan a todos los trabajadores generen una adhesión forzosa al paro. Con subtes, colectivos, colegios y estaciones de servicio funcionando los días de paro; se lograría evitar bastante que aquellas personas que no quieren parar se vean obligadas a hacerlo a pesar de su decisión.  Presentado el <b>10/4/2025</b> Expediente <strong>1035-D-2025</strong>",
  5: "<b>5. RECOLECCIÓN DE RESIDUOS COMO SERVICIO PÚBLICO ESENCIAL</b> Presenté un proyecto para que que los recolectores de basura no puedan hacer un paro tal que haga que se llene la Ciudad de basura. Hoy la Ciudad amaneció siendo una mugre porque ayer los recolectores de basura decidieron sumarse al paro. Ya ha pasado en otras discusiones que se usa a la basura como una forma de presionar a los gobiernos. Hay que dejarse de joder y poner límites a la protesta. La basura no puede ser un instrumento de extorsión (Recuerden sacar la basura de 19 a 21 y tirarla dentro del tacho). Presentado el <b>11/4/2025</b> Expediente <b>1039-D-2025</b> ",
  6: "<b>6. CREAR LA CALLE -VÍA BIBAS- EN VÍA VIVA</b> Presenté un proyecto para crear una calle peatonal denominada -Vía Bibas-, en homenaje a la familia Bibas - Silberman, donde actualmente funciona el paseo comercial Vía Viva, en el barrio de Belgrano. Actualmente la calle donde funciona el paseo gastronómico ubicado cerca del Barrio Chino, no es reconocida topográficamente como una calle formal en la Ciudad de Buenos Aires. Esto se debe a que es una calle creada hace poco por la elevación de las vías del tren y, por ende, carece todavía de una denominación legal otorgada por la Legislatura. ",
  7: "<b>7.EXENCIÓN DE INGRESOS BRUTOS PARA TODOS LOS GRADUADOS UNIVERSITARIOS Y DE TERCIARIOS.</b> Actualmente los graduados universitarios de carreras de más de 3 años no debemos pagar ingresos brutos en la Ciudad de Buenos Aires. Propongo extender este beneficio a aquellos que se hayan formado tecnicaturas y terciarios a fin de fomentar la profesionalización. Este proyecto se va a tratar MAÑANA en la comisión de presupuesto en la Legislatura Porteña y puede representar un ahorro importante para muchos contribuyentes. Premiando a quienes invierten tiempo estudiando y generando más riqueza para nuestra Ciudad con mejores servicios. Presentado el <b>25/11/24</b> Expediente <b>3394-D-2024</b>  ",
  8: "<b>8. FIRMAS DIGITALES PARA INICIATIVAS POPULARES.</b> El proyecto propone modernizar la Ley N° 40 sobre Iniciativa Popular en la Ciudad de Buenos Aires. Gracias a esta ley, los ciudadanos pueden elaborar y presentar proyectos que deben ser tratados si logran juntar una gran cantidad de firmas. El problema es que actualmente solo se puede hacer con firmas físicas, lo cual favorece al fraude y representa un esfuerzo enorme para los que quieren hacerlo seriamente.  Presentado el <b>5/12/23</b> Expediente <b>2731-D-2023</b> ",
  9: "<b>9. ATENCIÓN MÉDICA PRIORITARIA PARA PORTEÑOS EN HOSPITALES PÚBLICOS.</b> El proyecto establece que los hospitales públicos de la Ciudad de Buenos Aires deben atender con prioridad a las personas con domicilio legal en la ciudad.  El proyecto se fundamenta en la alta demanda de pacientes no porteños —especialmente de la provincia de Buenos Aires— que sobrecarga el sistema de salud local, dificultando el acceso a turnos por parte de quienes vivimos en la Ciudad de Buenos Aires. Presentado el <b>3/4/25</b> Expediente <b>988-D-2025</b>",
  10: "<b>10. RECOBRO A LAS PROVINCIAS DE ORIGEN POR LA ATENCIÓN HOSPITALARIA A ARGENTINOS NO RESIDENTES EN CABA.</b> El proyecto obliga al gobierno de la Ciudad a cobrar a otras provincias por la atención médica brindada a no residentes, incorporando esos ingresos al presupuesto de salud porteño. También faculta al Jefe de Gobierno a firmar acuerdos de reciprocidad sanitaria con otras jurisdicciones. Presentado el 3/4/25 Expediente 988-D-2025",
  11: "<b>11. COBRO DE LA ATENCIÓN MÉDICA EN HOSPITALES PÚBLICOS A EXTRANJEROS NO RESIDENTES.</b> El proyecto de ley busca asegurar el acceso igualitario al sistema de salud pública de la Ciudad de Buenos Aires para personas extranjeras con residencia permanente o temporaria, mientras que establece la obligación de contar con seguro médico o abonar por los servicios para quienes no tengan residencia legal en la Ciudad.  Presentado el <b>23/10/24</b> Expediente <b>3095-D-2024</b>",
  12: "<b>12. FICHA LIMPIA.</b> Este proyecto busca crear un sistema de ficha limpia para la Ciudad de Buenos Aires, impidiendo que personas con condena en doble instancia puedan ser candidatos para cargos electivos en la Ciudad de Buenos Aires. Presentado el <b>5/7/24</b>  Expediente <b>1903-D-2024</b>",
  13: "<b>13. LIBRE ELECCIÓN DE MEDIOS DE PAGO EN EL TRANSPORTE PÚBLICO.</b> El proyecto propone que, además de la tarjeta SUBE, los usuarios del transporte público de la Ciudad Autónoma de Buenos Aires puedan abonar sus viajes con tarjetas bancarias sin contacto, billeteras digitales, códigos QR u otros medios electrónicos. Esto incluye al subte, premetro y colectivos que operan exclusivamente en la ciudad. El objetivo es facilitar el acceso, evitar trámites engorrosos y desmonopolizar el sistema de pagos, fomentando la competencia y la comodidad para los usuarios. La autoridad de aplicación será la Secretaría de Transporte, que podrá ampliar medios de pago y coordinar con autoridades nacionales para mantener beneficios vigentes como la Tarifa Social.  Presentado el <b>9/4/24</b>  Expediente <b>0881-D-2024</b>",
  14: "<b>14. ORDENAMIENTO DEL FESTEJO DE LOS CARNAVALES EN LA CIUDAD: BASTA DE CORTES Y SUBSIDIOS.</b> El proyecto de ley propone reorganizar las prácticas y los festejos del Carnaval Porteño para que se realicen en plazas, parques, centros culturales y clubes, evitando el corte de calles. Establece que las prácticas se realicen en espacios con acondicionamiento acústico adecuado para no afectar a los vecinos, y deroga leyes y ordenanzas anteriores que promovían la realización de corsos en la vía pública. Es decir, que se practique y ejecuten donde no molesten. El objetivo es reducir el impacto en el tránsito, el descanso y la seguridad de los ciudadanos, así como optimizar el gasto público —que en 2025 superó los $1.000 millones— destinando los recursos a otras prioridades Presentado el 9/2/24 Expediente <b>2898-D-2023</b>",
  15: "<b>15. FIN DEL SUBSIDIO TOTAL A LA ENERGÍA ELÉCTRICA EN VILLAS Y BARRIOS POPULARES.</b> El proyecto de ley propone terminar con la absurda política de subsidios actual que hace que los porteños paguemos la totalidad del consumo eléctrico de todas las villas y barrios populares de la CABA. Esto lleva a todo tipo de distorsiones, abusos e inequidades. Por tal motivo propongo cortar con el regalo eléctrico y avanzar a una lógica de medidores por hogar, a fin de que cada cual pueda hacerse cargo de sus consumos.  Aquellas familias que requieran una asistencia por alguna cuestión socioeconómica seguirán teniendo el amparo de la tarifa social dispuesta por el Gobierno Nacional. Pero hay que dejar de subsidiar el 100% de todo lo que acontece dentro de los barrios. Presentado el 12/4/25 Expediente <b>1058-D-2025</b>",
  16: "<b>16. CREACIÓN DEL PROGRAMA DE INSPECCIÓN POLIVALENTE.</b> El proyecto propone centralizar la fiscalización comercial en la Ciudad de Buenos Aires mediante un cuerpo único de Inspectores Polivalentes bajo la Agencia Gubernamental de Control, excluyendo los controles tributarios y laborales. Hoy cada local recibe la visita de al menos 6 cuerpos inspectivos distintos, robándole una cantidad innecesaria de horas y representando un gasto público mayor al necesario. Se transfieren y amplían funciones de distintos organismos a esta agencia, incluyendo controles de higiene urbana, publicidad exterior y residuos.  Además, se establece la obligación de notificar con al menos 30 días hábiles de anticipación cualquier inspección (excepto las laborales o tributarias), bajo pena de nulidad.  El objetivo es evitar duplicidad de inspecciones, reducir costos y simplificar el procedimiento para los comerciantes. Presentado el <b>17/1/24</b> Expediente <b>2851-D-2023</b>",
  17: "<b>17. TERMINAR CON LA EXIGENCIA DE CAMPANAS EXTRACTORAS CARÍSIMAS DONDE NO SON NECESARIAS.</b> El proyecto de ley propone modificar el Código de Edificación de la Ciudad de Buenos Aires para actualizar los requisitos técnicos de cocinas y espacios para cocinar, incluyendo dimensiones mínimas, ventilación e iluminación. Se introduce la posibilidad de exceptuar la obligación de instalar campanas extractoras cuando los alimentos solo se calientan y no se cocinan, o en cocinas con escaso uso de fuego. Esta modificación busca reducir costos para pequeños negocios y eventos temporales, y facilitar su instalación sin comprometer las normas de higiene y seguridad alimentaria. Presentado el <b>3/5/24</b> Expediente <b>1190-D-2024</b>",
  18: "<b>18. CORTAR EL MILLONARIO E INEFICIENTE SUBSIDIO A LOS -MEDIOS VECINALES-</b> El proyecto propone derogar la Ley 2587, que desde 2007 establece un régimen de financiamiento publicitario para los medios vecinales de comunicación social de la Ciudad de Buenos Aires. Hoy implica un costo en el orden de los $5.000.000.000 que le aportan poco valor a la ciudadanía. Presentado el <b>22/10/24</b>  Expediente <b>3076-D-2024</b>",
  19: "<b>19. MAYOR SEGURIDAD EN EL SERVICIO DE SUBTERRÁNEOS: SENSORES EN PUERTAS QUE BLOQUEEN EL ARRANQUE  INSEGURO.</b> El proyecto de ley establece la incorporación obligatoria de un sistema de interbloqueo de puertas en todas las formaciones del subte de la Ciudad de Buenos Aires, que impida el inicio de la marcha de la formación si alguna puerta no está completamente cerrada y asegurada. Esta medida busca prevenir accidentes como el ocurrido en marzo de 2025 en la Línea B, donde una mujer resultó gravemente herida ya que la formación arrancó mientras su pierna quedó atrpada en la puerta del subte y como resultado del daño recibido tuvieron que amputarle la pierna. Presentado el <b>7/4/25</b>  Expediente <b>1005-D-2025</b>",
  20: "<b>20. DEVOLUCIÓN DE ABL Y PATENTES POR EL AHORRO DEL COSTO DE LAS PASO.</b> El proyecto de ley propone aplicar una bonificación impositiva de hasta el 100% en el Impuesto Inmobiliario, la Tasa de ABL y Patentes vehiculares a los contribuyentes de la Ciudad de Buenos Aires, utilizando los $20.000.000.000 ahorrados por la suspensión de las elecciones PASO en 2025. Ya que se suspendieron las PASO con la excusa de ahorrarle tiempo y dinero a los contribuyentes, corresponde que ese dinero vuelva a la gente y no quede en manos de los políticos. La medida busca devolver ese ahorro a los vecinos, premiando su aporte al sostenimiento de la Ciudad y promoviendo una gestión eficiente, transparente y orientada al beneficio directo de la ciudadanía.  Presentado el <b>24/2/25</b> Expediente <b>3761-D-2024</b>",
  21: "<b>21. ESTABLECER UN LÍMITE RAZONABLE DE ALCOHOL EN SANGRE PARA ACOMPAÑANTES DE MOTOS.</b> El proyecto de ley modifica el Código de Tránsito de la Ciudad de Buenos Aires para establecer que el acompañante de un motovehículo no podrá circular si supera los 0,5 g/l de alcohol en sangre. Este cambio resulta necesario a partir del surgimiento de nuevos servicios de transporte como UBER y Didi moto. En estos casos, el acompañante deberá descender del vehículo, se le labrará una infracción y no podrá volver a subirse. El conductor no será sancionado si su propio  nivel de alcoholemia es legal. La propuesta busca clarificar responsabilidades, evitar sanciones injustas al conductor y reforzar la seguridad vial mediante la responsabilidad individual. Presentado el <b>2/1/25</b>   Expediente <b>3626-D-2024</b>",
  22: "<b>22. PERMITIR LA LIBRE CIRCULACIÓN DE VEHÍCULOS EN EL CENTRO PORTEÑO.</b> El proyecto de ley propone derogar la Ley N.° 5.786, que estableció el Área Ambiental Buenos Aires Centro, la cual prohibe el acceso en automovil al centro porteño, ya que las condiciones urbanas han cambiado significativamente desde su sanción en 2016. La reducción de la población flotante, el aumento del trabajo remoto y el descenso de la contaminación sin necesidad de restricciones vehiculares han disminuido la efectividad de la norma. Además, se documenta un fuerte impacto económico negativo en el comercio, el empleo y el mercado inmobiliario de la zona. Si es que alguna vez tuvo sentido esta norma, en el presente sus consecuencias son netamente negativas. Presentado el <b>4/12/24</b>   Expediente <b>3497-D-2024</b>",
  23: "<b>23. MODIFÍCASE LA DENOMINACIÓN DE LA ACTUAL CALLE “REPÚBLICA BOLIVARIANA DE VENEZUELA” POR LA DE “REPÚBLICA DE VENEZUELA” </b>",
  24: "<b>24. PROCESO EJECUTIVO DE DESALOJO POR FALTA DE PAGO (DESALOJO EXPRESS I).</b>El proyecto de ley crea un proceso ejecutivo de desalojo por falta de pago en la Ciudad de Buenos Aires, al que las partes podrán adherir de forma optativa al firmar un contrato de alquiler. Este régimen permite que, si el locatario no realiza dos pagos consecutivos del alquiler en una cuenta bancaria especialmente abierta y registrada en el Banco Ciudad, el banco emita una certificación de incumplimiento que funcionará como título ejecutivo, facilitando un desalojo rápido y con escasas posibilidades de defensa. Presentado el <b>4/4/25</b>  Expediente <b>0994-D-2025</b>",
  25: "<b>25. DESALOJO EXPRESS EN 5 DÍAS EN LA CABA Y QUITA DE SUBSIDIOS PARA OKUPAS (DESALOJO EXPRESS II).</b> El proyecto incorpora al Código Contravencional porteño una figura que sanciona con trabajo comunitario, multa y la inhabilitación para recibir subsidios a quienes ocupen inmuebles sin poder acreditar la legalidad de su ocupación demás, si el propietario o tenedor legal denuncia la situación, el juez podrá ordenar el desalojo inmediato si el ocupante no justifica documentalmente su derecho en un plazo de cinco días. Con esta medida vamos a lograr aumentar la oferta de propiedades en alquiler de la Ciudad de Buenos Aires logrando así que se baje el precio de los alquileres. Presentado el <b>4/4/25</b>  Expediente <b>0993-D-2025</b>",
  26: "<b>26. BENEFICIOS FISCALES POR CONTRATAR TRABAJADORES CON DISCAPACIDAD.</b> El proyecto de ley propone modificar el artículo 243 del Código Fiscal para ampliar los beneficios fiscales a empleadores que contraten personas con discapacidad. Presentado el <b>6/1/25</b>  Expediente <b>1136-D-2025</b>",
  27: "<b>27. BENEFICIOS FISCALES POR CONTRATAR VETERANOS DE LA GUERRA DE LAS ISLAS MALVINAS.</b> El proyecto de ley propone incorporar un beneficio fiscal en el Código Fiscal de la Ciudad de Buenos Aires para incentivar la contratación de ex combatientes héroes de la Guerra de Malvinas, Georgias, Sándwich e Islas del Atlántico Sur. Los empleadores que contraten a estos veteranos podrán deducir el 100% de las contribuciones patronales abonadas del Impuesto sobre los Ingresos Brutos. La medida busca reparar una deuda histórica con quienes defendieron la soberanía nacional y enfrentan dificultades económicas, sociales y laborales, reconociendo su valor mediante inclusión laboral y alivio fiscal para las empresas que los empleen. También se permitirá aplicar el beneficio a veteranos ya contratados al momento de la entrada en vigencia de la norma.  Presentado el <b>21/04/2025</b> Expediente <b>1137-D-2025</b>",
  28: "<b>28. BENEFICIOS FISCALES POR CONTRATAR A PERSONAS MAYORES.</b> El proyecto de ley propone incorporar un beneficio fiscal en el Código Fiscal de la Ciudad Autónoma de Buenos Aires para incentivar la contratación y retención de personas mayores. Establece que los contribuyentes que desarrollen actividades productivas, comerciales o de servicios podrán deducir entre el 50% y el 100% de las contribuciones patronales abonadas por trabajadores mayores, conforme a la Ley 6753 y otras normativas nacionales. Esta medida busca fomentar la inclusión laboral de personas mayores, combatir la discriminación por edad y reconocer su aporte a la sociedad, al tiempo que ofrece un alivio impositivo a los empleadores. También contempla una cláusula transitoria para que el beneficio alcance a quienes ya tengan personas mayores empleadas. Presentado el <b>21/04/2025</b> Expediente <b>1138-D-2025</b>",
  29: "<b>29. ELIMINACIÓN DEL NOMBRE DE RODOLFO WALSH EN ESPACIOS PÚBLICOS DE LA CIUDAD.</b> Presenté cinco proyectos de ley para sustituir el nombre de Rodolfo Walsh en distintos espacios públicos de la Ciudad Autónoma de Buenos Aires, en virtud de un fallo judicial que lo vincula con la planificación del atentado del 2 de julio de 1976 en la Superintendencia de Seguridad Federal, que causó 23 muertes y más de 100 heridos, y cuya responsabilidad torna éticamente inadmisible su homenaje en el ámbito público. Presentado el <b>20/12/2024</b>  Expediente <b>3600-D-2024</b> Presentado el <b>21/11/2024</b> Expediente <b>3396-D-2024</b>",
  30: "<b>30. QUE LOS PRESOS SE HAGAN CARGO DEL COSTO DE SU DETENCIÓN</b> El proyecto de ley crea un Sistema de Reintegro de Gastos para que las personas privadas de su libertad en la Ciudad Autónoma de Buenos Aires, una vez condenadas, afronten los costos de su detención, estimados en $27.000 diarios por persona. En caso de no poder abonarlos, deberán realizar trabajos en los establecimientos como forma de compensación, siempre bajo condiciones que respeten la dignidad humana y la proporcionalidad de esfuerzos. Presentado el <b>19/12/2024</b>  Expediente <b>3596-D-2024</b>",
  31: "<b>31. REDUCCIÓN DEL NÚMERO DE DEFENSORES DEL PUEBLO ADJUNTOS.</b> El proyecto propone reducir de cinco a uno el número de Defensores del Pueblo Adjuntos en la Ciudad Autónoma de Buenos Aires,  con el fin de adecuarla a principios de austeridad ante la crisis económica actual. Además, se elimina la exigencia de paridad de género entre los designados. La iniciativa busca optimizar recursos y fortalecer la confianza ciudadana en las instituciones. Menos cargos políticos, menos gasto público, menos impuestos.",
  32: "<b>32. REDUCCIÓN DEL NÚMERO DE COMUNEROS QUE COBRAN DE 7 A 1.</b> El proyecto de ley propone que solo el presidente de cada Junta Comunal, hay 15 comunas, reciba una remuneración equivalente al 70% del ingreso bruto de un diputado de la Ciudad (aprox 3.5 millones de pesos), mientras que el resto de los miembros desempeñarán sus funciones ad honorem a partir del próximo mandato. Presentado el <b>19/11/2024</b>  Expediente <b>3347-D-2024</b>",
  33: "<b>33. REGLAMENTAR LA LEY DE MECENAZGO CIENTÍFICO. ESTA ES UNA LEY SANCIONADA YA, DE MI AUTORÍA.</b> Crea un régimen de promoción fiscal que incentive a las empresas a financiar proyectos de investigación científica, tecnológica e innovación en áreas estratégicas, con el objetivo de impulsar el desarrollo productivo, industrial y comercial, mejorar la calidad de vida de la población y fortalecer el vínculo entre el sector público, privado y académico. Gracias a esto, los contribuyentes podrán destinar parte del dinero que pagan en concepto de impuestos a financiar proyectos de ciencia, tecnología e innovación. Pero para que la ley entre en vigencia falta que el Poder Ejecutivo la reglamente. Presentado el <b>10/4/2024</b> Expediente <b>0907-D-2024</b>",
  34: "<b>34. EXIGIR QUE EL JEFE DE GOBIERNO, LOS LEGISLADORES Y LOS COMUNEROS TENGAN SECUNDARIO COMPLETO (Ley Zaracho).</b> Hoy te piden tener título secundario para poder acceder a casi cualquier trabajo en el Gobierno de la Ciudad. Sin embargo, por una omisión legal, no resulta requisito para poder ocupar cargos electivos en la Ciudad de Buenos Aires. El fundamento principal es elevar la calidad democrática asegurando que los representantes cuenten con una formación mínima acorde con la creciente complejidad de los desafíos públicos. Presentado el <b>6/3/2024</b> Expediente <b>0549-D-2024</b>",
  35: "<b>35. LIBRE INGRESO DE ANIMALES DOMÉSTICOS DE COMPAÑÍA EN COMERCIOS</b> (si el dueño del local quiere). Hasta ahora estaba prohibido, por ley, entrar con mascotas a una serie de comercios de la CABA. Nuestro proyecto busca levantar esta prohibición y darle la opción a los locales de dejar, o no, acceder a mascotas. La iniciativa busca fomentar una convivencia más inclusiva y alineada con los cambios culturales en torno al bienestar animal. Presentado el <b>24/04/2025</b>  Expediente <b>1172-D-2025</b>",
  36: "<b>36. POSIBILITAR INGRESO DE ANIMALES DOMÉSTICOS DE COMPAÑÍA EN DEPENDENCIAS DEL GOBIERNO DE LA CIUDAD.</b> El proyecto de ley modifica la normativa vigente para permitir el ingreso transitorio de animales domésticos en dependencias del Gobierno de la Ciudad Autónoma de Buenos Aires, salvo cuando exista una prohibición expresa fundada en razones de salubridad, seguridad o funcionamiento específico del área. Así voy a poder recibir a vecinos con sus mascotas en la Legislatura (eso si, traigan bolsitas y toallitas para hacerse cargo de cualquier accidente). Presentado el <b>24/04/2025</b>  Expediente <b>1172-D-2025</b>",
  37: "<b>37. POSIBILITAR EL TRASLADO DE MASCOTAS EN TRANSPORTE PÚBLICO.</b> El proyecto de ley busca permitir que las personas puedan viajar con sus mascotas en el transporte público cumpliendo con medidas básicas de seguridad e higiene cualquier día y en cualquier momento. Actualmente, sólo podés viajar con mascotas los días feriados y domingos durante todo el día, y los sábados después de las 13 :00 horas, podés viajar con tu mascota en el subte. Presentado el <b>24/04/2025</b>   Expediente <b>1207-D-2025</b>",
  38: "<b>38. BENEFICIOS FISCALES PARA REFUGIOS DE ANIMALES.</b> Se busca modificar la norma que establece las exenciones impositivas en la Ciudad de Buenos Aires para que no solo contemple a las -Sociedades protectoras de animales- sino también a las simples asociaciones que funcionen como refugios. Así evitamos que tengan que destinar dinero al pago de impuestos y pueden enfocarse de mejor manera a asistir a los animales en tránsito. Presentado el <b>24/04/2025</b>   Expediente <b>1186-D-2025</b>",
  39: "<b>39. SANCIONES PARA QUIENES NO LEVANTEN LA CACA DE SUS MASCOTAS.</b> El proyecto busca mejorar la convivencia responsabilizando a quienes optan por dejar caca en la viva pública. Amamos a las mascotas pero conllevan responsabilidades. No solo el deber de tratarlas bien y cuidarlas sino también de evitar que perjudiquen a terceros. Con esta ley cada uno se hace cargo de sus cacas. Presentado el <b>24/04/2025</b>  Expediente <b>1208-D-2025</b>",
  40: "<b>40. LEY ANTI-TOMA DE COLEGIOS.</b> El proyecto busca impedir que se tomen Escuelas, facultado a las fuerzas de seguridad a desalojar a quienes busquen llevar adelante medidas de fuerza qué impidan el normal desenvolvimiento de las clases. Presentado el <b>24/04/2025</b>  Expediente <b>1212-D-2025</b>",
  41: "<b>41. ESPACIO RESERVADO PARA DETENCIÓN DE VEHÍCULOS FRENTE A ESTABLECIMIENTOS VETERINARIOS</b> El proyecto busca impedir que se tomen Escuelas, facultado a las fuerzas de seguridad a desalojar a quienes busquen llevar adelante medidas de fuerza qué impidan el normal desenvolvimiento de las clases.Presentado el <b>25/04/2025<7b>    Expediente <b>1228-D-2025</b>",
  42: "<b>42. CREACIÓN DE DÁRSENAS PARA URGENCIAS VETERINARIAS</b> El proyecto busca permitir la creación de dársenas frente a establecimientos veterinarios que atiendan urgencias, equiparándolos a escuelas y centros de salud en cuanto a derechos de accesibilidad. La norma contempla que, mediante estudios técnicos de la autoridad competente, estos espacios puedan ser habilitados para el ascenso y descenso de animales, reforzando el carácter sanitario de estos servicios. Presentado el <b>25/04/2025</b>   Expediente <b>1228-D-2025</b>",
  43: "<b>43. ELIMINACIÓN DEL IMPUESTO A EMBARCACIONES DEPORTIVAS O DE RECREACIÓN</b> El proyecto de ley propone eliminar el impuesto a las embarcaciones deportivas o de recreación en la Ciudad de Buenos Aires, al considerar que su cobro es inconstitucional por superponerse con el Impuesto Nacional a los Bienes Personales, lo cual está prohibido por la Ley de Coparticipación Federal. A diferencia de los automotores, estas embarcaciones no tienen patente sino matrícula, administrada por la Prefectura Naval, lo que refuerza la competencia federal. Además, se señala su carácter confiscatorio, ya que las alícuotas actuales podrían llevar a que, en pocos años, se tribute un monto equivalente a más de la mitad del valor del bien. Presentado el <b>25/04/2025</b>   Expediente <b>1229-D-2025</b>",
  44: "<b>44. APLICACIÓN DE LEY DE HONORARIOS LOCAL A LOS FUEROS NACIONALES</b> Este proyecto de ley propone una modificación de la Ley 5134 de Honorarios Profesionales de Abogados y Procuradores de la Ciudad Autónoma de Buenos Aires, con el objetivo de ampliar su ámbito de aplicación a los juzgados nacionales. Además, se deroga la cláusula transitoria que condicionaba la aplicación del régimen de honorarios locales a la integración de los fueros nacionales al Poder Judicial de la Ciudad. Los fundamentos destacan que la regulación de honorarios es una facultad propia de los gobiernos locales y que la existencia de dos regímenes distintos de honorarios (uno local y otro nacional) genera una desigualdad y vulnera el principio de igualdad ante la ley. Se busca fortalecer la autonomía de la Ciudad y garantizar la igualdad de los profesionales porteños que intervienen en los tribunales nacionales. Presentado el <b>25/04/2025</b>  Expediente <b>1230-D-2025</b>",
  45: "<b>45. DISOLUCIÓN Y LIQUIDACIÓN DE OBRA SOCIAL DE LA CIUDAD DE BUENOS AIRES (OBSBA)</b> Este proyecto de ley busca la disolución y liquidación de la Obra Social de la Ciudad de Buenos Aires (ObSBA). En cuanto a la liquidación, se determina que cesará la percepción de aportes a la Obra Social y que los afiliados podrán derivar sus aportes a otros agentes del seguro de salud habilitados. Presentado el <b>25/04/2025</b>    Expediente <b>1231-D-2025</b>",
  46: "<b>46. LIBRE ELECCIÓN DE OBRA SOCIAL PARA TRABAJADORES MUNICIPALES DE LA CIUDAD DE BUENOS AIRES</b> El proyecto de ley tiene como objetivo principal desregular la actual estructura de la Obra Social de la Ciudad de Buenos Aires (OBSBA), permitiendo a los afiliados la libre elección de su obra social, sin restricciones ni condicionamientos. Si bien el gobierno nacional ha permitido la libre opción para trabajadores a lo largo del país, esto no alcanza a empleados provinciales, los cuales siguen esclavos de las obras sociales locales. Más libertad, más competencia, mejores servicios. Presentado el <b>25/04/2025</b>  Expediente <b>1232-D-2025</b> ",
  47: "<b>47. ELIMINACIÓN PRESUPUESTO CON PERSPECTIVA DE GÉNER</b> El proyecto de ley propone derogar la Ley Nº 6170, que incorporó perspectiva de género al presupuesto de la Ciudad Autónoma de Buenos Aires, al considerarse inconstitucional, ya que introduce distinciones basadas en género que vulneran el principio de igualdad consagrado en la Constitución Nacional y en la de la Ciudad Autónoma de Buenos Aires. La incorporación de la -etiquetación- de programas y la desagregación de datos por género infringen el artículo 16 de la Constitución, que garantiza la igualdad ante la ley para todos los ciudadanos. Presentado el <b>25/04/2025</b>  Expediente <b>1233-D-2025</b>",
  48: "<b>48. PROHIBICIÓN DE VENTA AMBULATORIA EN RESTAURANTES Y BARES</b> El proyecto de ley busca endurecer las penas, dentro del ámbito contravencional, sobre quienes ejercen la venta ambulatoria en espacios privados (bares, restaurantes, cafés y establecimientos gastronómicos), para prevenir situaciones delictivas y velar por la tranquilidad y el cuidado del espacio privado de las personas. Presentado el <b>25/04/2025</b>  Expediente <b>1234-D-2025</b> ",
  49: "<b>49. PRESUNCIÓN PROCESAL DE LEGÍTIMA DEFENSA</b> El proyecto de ley tiene como objetivo reforzar y garantizar los principios constitucionales del debido proceso, el derecho de defensa y la presunción de inocencia, modificando el artículo 2º del Anexo A de la Ley 2303, incorporando expresamente la presunción de la duda en favor del imputado o imputada cuando se trate de casos de legítima defensa; y reformando el artículo 212 inciso c), para incorporar una presunción de legítima defensa en aquellos casos donde la persona imputada haya impedido o repelido razonablemente un ataque perpetrado con arma blanca o de fuego. Presentado el <b>25/04/2025<b>   Expediente <b>1237-D-2025</b>",
  50: "<b>50. RACIONALIZACIÓN DEL USO DE VEHÍCULOS OFICIALES</b> El proyecto de ley prohíbe el uso de vehículos oficiales por parte de funcionarios de la Ciudad Autónoma de Buenos Aires, salvo para el Jefe de Gobierno, Vicejefe de Gobierno y Ministros, quienes podrán utilizarlos exclusivamente en el ejercicio de sus funciones. Los vehículos que queden sin uso deberán ser devueltos en un plazo de 30 días y subastados públicamente por el Banco Ciudad, destinándose los fondos obtenidos al Tesoro de la Ciudad. Presentado el <b>25/04/2025</b>   Expediente <b>1238-D-2025</b> ",
  51: "<b>51.PROTOCOLO ANTIPIQUETE</b> El proyecto de ley establece un protocolo de actuación ante manifestaciones públicas que bloqueen calles o avenidas en la Ciudad Autónoma de Buenos Aires. Se prevén instancias de negociación, sanciones contravencionales para quienes cometan infracciones y multas agravadas si hay violencia o daños. También se crea un Fondo Especial con lo recaudado por multas, destinado a mejorar las condiciones laborales de las fuerzas de seguridad.  Presentado el <b>25/04/2025</b>   Expediente <b>1243-D-2025</b>",
  52: "<b>52. OBLIGACIÓN DE LIBERAR CARRILES DE CIRCULACIÓN DURANTE MANIFESTACIONES</b> El proyecto establece que las manifestaciones públicas solo podrán realizarse sobre las veredas, para garantizar la libre circulación. Si se bloquean calles por cuestiones de fuerza mayor, se debe asegurar la libre circulación de al menos dos carriles en avenidas, corredores de Metrobús y carriles exclusivos, y de un carril en las demás vías. Si no se cumple, se actuará bajo el régimen de flagrancia, con intervención judicial y posible disolución de la protesta. Presentado el <b>25/04/2025</b>   Expediente <b>1243-D-2025</b>",
  53: "<b>53. INTEGRACIÓN VOLUNTARIA DE CÁMARAS PRIVADAS AL SISTEMA PÚBLICO INTEGRAL DE VIDEO VIGILANCIA</b> El proyecto de ley establece que quienes instalen cámaras en sus casas o comercios podrán registrarlas y conectarlas al sistema de seguridad público, siempre que cumplan con requisitos técnicos. Así se fortalece la cobertura y se potencia al trabajo de la policía, los jueces y fiscales. A cambio, recibirán una exención del 10% del Impuesto Inmobiliario y ABL, ampliable al 20% para consorcios con mayor cobertura. La iniciativa busca aprovechar cámaras ya instaladas por vecinos, consorcios o comercios para reforzar la seguridad sin duplicar recursos ni aumentar el gasto estatal de manera significativa. También permite el acceso rápido a imágenes útiles para prevenir, intervenir en flagrancia y esclarecer delitos. Presentado el <b>25/04/2025</b>  Expediente <b>1250-D-2025</b> ",
  54: "<b>54. ASIGNACIÓN PRIORITARIA DE VACANTES EN ESCUELAS PÚBLICAS A LOS PORTEÑOS</b> El proyecto de ley propone establecer un orden de prioridad en la asignación de vacantes en las escuelas públicas de la Ciudad Autónoma de Buenos Aires. En primer lugar, se priorizará a los aspirantes nacidos y domiciliados en la ciudad, luego a los domiciliados en ella, y, finalmente, a otras prioridades que determine la autoridad de aplicación. Esta medida busca solucionar la crisis de vacantes y garantizar el derecho a la educación, evitando desigualdades territoriales y sociales, además de optimizar los recursos educativos para los habitantes de la ciudad. Presentado el <b>25/04/2025</b>  Expediente <b>1251-D-2025</b>",
  55: "<b>55.LEY ANTI CANDIDATURAS TESTIMONIALES</b> El proyecto de ley establece un régimen de inhabilidad temporaria para aquellos que resulten electos en cargos públicos de la Ciudad Autónoma de Buenos Aires y renuncien antes de cumplir dos (2) años desde la fecha de asunción, o no asuman el cargo para el que fueron electos dentro de ese plazo.En criollo, quienes resulten electos y no asuman y ejerzan su cargo electivo no podrán ocupar ningún tipo de cargo público durante el período que hubieran tenido que ocupar el cargo para el cual fueron electos. Presentado el <b>25/04/2025</b>  Expediente <b>1253-D-2025</b>",
  56: "<b>56. REGISTRO DE MANDATARIOS Y MANDANTES DE LA CIUDAD</b> El proyecto de ley propone la creación del Registro de Mandatarios y Mandantes de la Ciudad Autónoma de Buenos Aires, gestionado por el Ministerio de Justicia. Este registro almacenará las escrituras públicas de mandato, proporcionando mayor transparencia y seguridad jurídica a los actos celebrados mediante mandato, conforme al Código Civil y Comercial de la Nación. Presentado el <strong>25/04/2025</strong>    Expediente <strong>1254-D-2025</strong>",
  57: "<b>57. SANCIONES POR PROMOCIÓN O DIFUSIÓN DE OFERTAS ENGAÑOSAS POR MEDIOS DIGITALES</b> (responsabilidad concurrente de influencers por promocionar estafas) Este proyecto de ley propone la incorporación de un artículo al Código Contravencional de la Ciudad de Buenos Aires para sancionar la promoción o difusión de ofertas engañosas a través de medios electrónicos.Presentado el <b>25/04/2025</b>  Expediente <b>1255-D-2025</b> ", 
  58: "<b>58. PROHIBICIÓN DE ARENADO CON SÍLICE</b> El proyecto de ley propone prohibir en la Ciudad Autónoma de Buenos Aires el uso del chorro de arena con sílice (arenado o hidroarenado), debido a su comprobada peligrosidad para la salud de los trabajadores y de las personas expuestas en las inmediaciones.  Presentado el <b>25/04/2025</b>   Expediente <b>1256-D-2025</b>",
  59: "<b>59. MODIFICACIÓN DEL RÉGIMEN PROCESAL PENAL JUVENIL</b> (menos pibes chorros y asesinos sueltos) El proyecto de ley propone modificar cuatro artículos del Régimen Procesal Penal Juvenil de la Ciudad Autónoma de Buenos Aires para adaptarlo al sistema acusatorio vigente y a las condiciones sociales actuales. Se busca ampliar los plazos de investigación penal preparatoria y prisión preventiva, considerando la insuficiencia de los plazos actuales para casos graves. Además, propone ajustar el plazo de prisión preventiva para menores de edad, siguiendo la legislación nacional. Finalmente, se ajusta el rol del Ministerio Público Fiscal en la remisión, aclarando su competencia en la concesión de salidas alternativas como la suspensión del proceso a prueba y la mediación.Presentado el <b>25/04/2025</b>    Expediente <b>1257-D-2025</b> ",
  60: "<b>60. LEY ANTI CARTONEO</b> El proyecto elimina el marco legal que permitía el cartoneo, derogando la Ley 992 de recuperadores urbanos y modificando la Ley 1854. Así, se prioriza un sistema de higiene urbana centralizado, dejando atrás el trabajo informal de los cartoneros, que durante años generó problemas en la recolección y el reciclado de residuos en la ciudad. También, establece sanciones para quienes extraigan residuos de los contenedores públicos con fines de comercialización. La infracción será sancionada con apercibimiento, decomiso y destrucción de los elementos y vehículos no motorizados usados. Si se utiliza un vehículo motorizado, se suma una multa de 500 a 1000 unidades fijas, y en caso de reiteración, se impondrán 10 días de arresto junto con las sanciones anteriores.Presentado el <b>01/04/2025</b>   Expediente <b>981-D-2025</b>", 
  61: "<b>61. HABILITAR LA VENTA Y CONSUMO DE BEBIDAS ALCOHÓLICAS DE FORMA RESPONSABLE EN ESTADIOS DEPORTIVOS</b> El proyecto de ley busca permitir la venta y consumo moderado de bebidas alcohólicas en los estadios de fútbol, y otros espectáculos, de la Ciudad de Buenos Aires. Se prohíbe el ingreso de personas en estado de embriaguez y se modifica el Código Contravencional para sancionar dicha conducta, incorporando agravantes por reiterancia. Presentado el <strong>26/02/2025</strong>   Expediente <strong>3766-D-2024</strong> ",
  62: "<b>62. HABILITAR LA PRESENCIA DE PÚBLICO VISITANTE EN ESTADIOS DE FÚTBOL</b> El proyecto de ley habilita la presencia de público visitante en los estadios de fútbol de la Ciudad de Buenos Aires, bajo estrictas medidas de seguridad, separación física y accesos diferenciados. Establece que el club local será responsable de financiar y coordinar el operativo de seguridad, con posibilidad de aporte del club visitante.  La propuesta busca mejorar la experiencia deportiva sin comprometer la seguridad ni los recursos públicos.Presentado el <b>26/02/2025</b>   Expediente <b>3765-D-2024</b> ", 
  63: "<b>63. ENTONACIÓN DEL HIMNO NACIONAL EN PARTIDOS DE FÚTBOL Y OTROS</b> El proyecto de ley propone que al inicio de cada partido deportivo se entonen las estrofas del Himno Nacional Argentino, con el objetivo de fortalecer la identidad nacional y promover la convivencia pacífica entre los asistentes, recordando valores comunes en un contexto donde la rivalidad puede generar divisiones. Presentado el <b>26/02/2025</b> Expediente <b>3765-D-2024</b>",
  64: "<b>64. LÍMITES A LAS DECLARACIONES LEGISLATIVAS A NÚMEROS REDONDOS</b> Esta iniciativa busca establecer límites a las declaraciones y conmemoraciones otorgadas por la Legislatura porteña, con el fin de ordenar y jerarquizar sus actos. Así ahorramos tiempo y recursos legislativos para conmemorar aniversarios solo cuando el número de años termine en 5 o 0, promoviendo austeridad. Que los políticos hagan plata con la suya, no con la tuya. Presentado el <b>23/10/2024</b> Expediente <b>3107-D-2024</b>",
  65: "<b>65. ESTABLECER AL PLÁTANO DE SOMBRA COMO ESPECIE NO APTA PARA LA CIUDAD (un centro a los alérgicos)</b> El proyecto de ley propone declarar al Plátano de Sombra (Platanus Acerifolia) como especie no apta para la Ciudad de Buenos Aires, prohibiendo su plantación y estableciendo su reemplazo por especies nativas de bajo impacto alergénico en caso de remoción. La iniciativa busca reducir los problemas de salud pública, ya que el polen de este árbol es altamente alergénico y afecta especialmente a personas con asma y rinitis. Presentado el <b>03/10/2024</b> Expediente <b>2906-D-2024</b>",
  66: "<b>66. LIMITAR LOS HONORARIOS DE LOS MANDATARIOS DEL GOBIERNO</b> El proyecto propone regular la actuación de los mandatarios judiciales que intervienen en ejecuciones fiscales por deudas tributarias en la Ciudad Autónoma de Buenos Aires.  Presentado el <b>06/03/2024</b>  Expediente <b>533-D-2024</b>",
  67: "<b>67. CREACIÓN DE LA IGJ LOCAL (SECABA)</b> El Proyecto de Ley crea la Superintendencia de Empresas de la Ciudad Autónoma de Buenos Aires (SECABA). Con el fin de realizar control y supervisión de sociedades, asociaciones y fundaciones con domicilio en la ciudad, así como de las sociedades extranjeras que operen en el ámbito local. Presentado el <b>28/04/2024</b>  Expediente <b>1261-D-2025</b>",
  68: "<b>68. ESPACIO PARA COMERCIOS ATENDIDOS POR  PERSONAS CON DISCAPACIDAD O EMPRESAS QUE LAS EMPLEAN</b> Este proyecto de ley propone modificar la Ley N° 899 para ampliar las oportunidades laborales para personas con discapacidad. Presentado el <b>28/04/2025</b> Expediente <b>1258-D-2025</b> ",
  69: "<b>69. ELIMINACIÓN DE LA VERIFICACIÓN TÉCNICA VEHICULAR (VTV) OBLIGATORIA> El proyecto de ley propone derogar el régimen obligatorio de Verificación Técnica Vehicular (VTV) en la Ciudad Autónoma de Buenos Aires, al considerar que su impacto en la seguridad vial es mínimo en comparación con los costos que impone a los ciudadanos en tiempo y dinero. En su lugar, plantea que los propietarios de vehículos asuman la responsabilidad de mantenerlos en condiciones seguras, junto a su compañía de seguros. Presentado el <b>28/04/2025</b> Expediente <b>1259-D-2025</b> ",
  70: "<b>70. TERMINAR CON LA OBLIGACIÓN DEL GRABADO DE AUTOPARTES</b> El proyecto de ley propone la derogación de la Ley Nº 3.708, que establece el grabado obligatorio de autopartes y el registro de desarmaderos de automóviles, quedando sin efecto el Registro de Verificación de Autopartes creado en el ámbito del Ministerio de Justicia y Seguridad del Poder Ejecutivo. Presentado el <b>15/03/2024</b> Expediente <b>668-D-2024</b>",
  71: "<b>71. INCORPORACIÓN DE LOS PLAZOS EN LOS ACUERDOS DE MEDIACIÓN PENAL</b> El proyecto de ley propone modificar el Código Procesal Penal de la CABA para permitir que los acuerdos de mediación penal puedan incluir plazos. Busca corregir una falencia actual que impide formalizar plazos en estos acuerdos, lo que en la práctica genera simulaciones o mediaciones indefinidas. La reforma apunta a brindar mayor transparencia, certeza y eficacia en la resolución de conflictos penales, mejorando el acceso a la justicia y la satisfacción de las partes involucradas. Presentado el <b>28/04/2025</b> Expediente <b>1262-D-2025</b>",
  72: "<b>72. CALLE -DIEGO ARMANDO MARADONA-</b> El proyecto de ley propone modificar el nombre de la calle -José Luis Cantilo- por -Diego Armando Maradona-, en homenaje al ídolo del fútbol. La calle se asocia con momentos significativos de la vida de Maradona, como la casa que compró para sus padres en 1981, donde vivió antes de convertirse en una figura internacional. Esta casa, cargada de historia personal y deportiva, fue testigo de varios eventos importantes en la vida del astro y se busca ponerla y su zona en valor como hito turístico porteño. Presentado el <b>28/04/2025</b> Expediente <b>1263-D-2025</b>",
  73: "<b>73. MAYOR PLAZO PARA LA RECARGA O MANTENIMIENTO DE LOS EXTINTORES (MATAFUEGOS)</b> El proyecto de ley propone modificaciones al Código de Edificación y al Régimen de Faltas de la Ciudad de Buenos Aires en relación con la recarga y mantenimiento de extintores (matafuegos). Se extiende la vigencia de la recarga de los extintores pasando de 12 meses a 18 meses, considerando avances en tecnología y eficiencia después de haberlo consultado con ingenieros y personas de la industria de los matafuegos. Presentado el <b>28/04/2025</b> Expediente <b>1264-D-2025</b>",
  74: "<b>74. ELIMINACIÓN DEL SUBSIDIO CULTURAL VITALICIO El proyecto de ley propone derogar la Ordenanza N° 44370, que otorga un subsidio mensual y vitalicio, heredable para artistas de la Ciudad.  La iniciativa busca eliminar privilegios, promover la igualdad ante la ley y optimizar el uso de los recursos públicos, permitiendo reasignarlos a políticas sociales más inclusivas y eficientes. Y que en todo caso se acompañe al arte con políticas más inteligentes que no generen una renta a perpetuidad sin contraprestaciones para la ciudadanía porteña. Presentado el <b>21/11/2024</b>  Expediente<b>3395-D-2024<",
  75: "<b>75. ELIMINACIÓN DE REGISTROS SOBRE MENSAJERÍA URBANA Y REPARTO A DOMICILIO</b> El proyecto de ley deroga la Ley N.º 6.314 y la Ley N.º 5.526. Elimina los registros RUTRAMUR y RUTRAMYC, y prohíbe que el Poder Ejecutivo imponga nuevos requisitos, permisos o condiciones a repartidores, plataformas o comercios relacionados. Presentado el <b>15/03/2024</b> Expediente <b>669-D-2024</b> ",
  76: "<b>76. MAYORES PENAS PARA QUIENES REALIZAN FALSAS DENUNCIAS BASADAS EN CUESTIONES DE GÉNERO</b> El proyecto de ley propone modificar el artículo 82 del Código Contravencional de la Ciudad de Buenos Aires para sancionar con mayor severidad las falsas denuncias. Establece que quien realice una denuncia falsa sobre una contravención podrá recibir penas que van desde trabajos de utilidad pública, multas o arresto de 5 días.  Presentado el <b>28/04/2025</b> Expediente <b>1260-D-2025</b> ",
  77: "<b>77. COMISIÓN LEGISLATIVA DE REVISIÓN PERIÓDICA DEL BUEN GOBIERNO</b> El proyecto de ley propone la creación de la Comisión de Revisión Periódica del Buen Gobierno, cuyo objetivo es evaluar la eficacia y eficiencia de las dependencias del Estado de la Ciudad Autónoma de Buenos Aires.  Presentado el <b>28/04/2025</b>  Expediente <b>1267-D-2025</b>",
  78: "<b>78. FORTALECIMIENTO DE LA AUTONOMÍA DEL TRIBUNAL SUPERIOR DE JUSTICIA DE LA CABA</b> La reforma busca fortalecer la autonomía de la CABA en general y del Tribunal Superior de Justicia de la Ciudad Autónoma de Buenos Aires en particular, alineándose con un fallo reciente de la Corte Suprema de Justicia de la Nación que reconoció la necesidad de que el tribunal local sea la última instancia recursiva, incluso en los fueros nacionales. El objetivo es garantizar que el Tribunal Superior de Justicia tenga competencia definitiva en los casos que involucren la interpretación de las constituciones nacional o local, consolidando su rol como máximo tribunal en la Ciudad Autónoma de Buenos Aires. Presentado el <b>28/04/2025</b> Expediente <b>1268-D-2025</b>",
  79: "<b>79. TERMINAR CON LAS VILLAS EN LA CABA</b> Se crea un programa para recuperar terrenos de barrios populares y garantizar acceso a viviendas dignas de sus ocupantes. Se expropiarán terrenos sin título formal para su urbanización mediante venta de los mismos en el mercado libre.Presentado el <b>28/04/2025</b>  Expediente <b>1270-D-2025</b> ",
  80: "<b>80. PREAUTORIZAR DIVULGACIÓN DE INFORMACIÓN E IMÁGENES PERSONALES ANTE SECUESTROS/DESAPARICIONES (ley Amber)</b> El proyecto de ley propone incorporar a la Ley N° 6483 de la Ciudad de Buenos Aires la posibilidad de inscripción anticipada y voluntaria en el Registro de personas con paradero desconocido y personas halladas con identidad desconocida.   Presentado el <b>28/04/2025</b> Expediente <b>1271-D-2025</b>",
  81: "<b>81. BAJA DE LA EDAD DE IMPUTABILIDAD</b> Este proyecto de ley propone modificar el Código Contravencional de la Ciudad de Buenos Aires, estableciendo la baja de la edad de imputabilidad a 14 años para las contravenciones. Además, se especifica que los menores de 18 años detenidos por contravenciones no serán alojados junto a adultos. La medida tiene como objetivo ampliar la acción del Poder Judicial para aquellos adolescentes que inician conductas disvaliosas, reconociendo la necesidad de complementar las políticas socioeducativas con un enfoque punitivo adecuado. Presentado el <b>28/04/2025</b> Expediente <b>1273-D-2025</b> ",
  82: "<b>82. LEY DE CÁRCELES PRIVADAS PARA LA CABA</b> El proyecto de ley establece la emergencia de seguridad pública en la Ciudad Autónoma de Buenos Aires, debido a la crisis del sistema carcelario por la sobrepoblación en alcaidías y otros espacios de detención.   Presentado el <b>28/04/2025</b> Expediente <b>1274-D-2025</b>",
  83: "<b>83. AUMENTAR PENAS POR MALTRATO ANIMAL</b> El proyecto de ley propone aumentar las sanciones por maltrato animal en la Ciudad Autónoma de Buenos Aires. Se establece un endurecimiento de las penas, incluyendo mayores multas, días de trabajo de utilidad pública y arresto para quienes omitan cuidados responsables, abandonen animales, mantengan animales en condiciones inadecuadas o menoscaben su integridad. Presentado el <b>28/04/2025</b>  Expediente <b>1277-D-2025</b> ",
  84: "<b>84.MAYORES CONTROLES Y SANCIONES PARA ADMINISTRADORES DE CONSORCIOS</b> Se propone que todos los administradores deban cumplir con un proceso de inscripción donde haya más información disponible para quienes los vayan a contratar que incluye la presentación de documentación sobre juicios en su contra y diversos antecedentes.  Presentado el <b>29/04/2025</b>  Expediente <b>1279-D-2025</b>",
  85: "<b>85. LEY ANTI NEPOTISMO</b>  El proyecto de Ley Anti Nepotismo propone modificar el Régimen de Integridad Pública de la Ciudad de Buenos Aires para prohibir la designación de familiares de funcionarios públicos de alto rango, tanto directos como por afinidad, hasta el segundo o tercer grado, según el caso, en cualquier área del sector público porteño. Presentado el <b>29/04/2025</b> Expediente <b>1281-D-2025</b> ",
  86: "<b>86. REFERÉNDUM Y CONSULTA POPULAR DIGITAL</b> El proyecto de ley propone la incorporación de un Sistema de Consulta Popular o Referéndum Digital en la Ciudad Autónoma de Buenos Aires, permitiendo a los electores participar en los procesos electorales mediante un portal digital. Presentado el<b>29/04/2025</b> Expediente <b>1295-D-2025</b> ",
  87: "<b>87. PREVENCIÓN E INTERVENCIÓN EN SITUACIONES DE ACOSO ESCOLAR Y CIBERACOSO</b> El proyecto de ley propone la incorporación de la capacitación obligatoria en prevención, detección e intervención ante el acoso escolar y ciberacoso para todo el personal docente y no docente de los niveles primario y secundario en escuelas públicas y privadas de la Ciudad de Buenos Aires.   Presentado el <b>29/04/2025</b> Expediente <b>1298-D-2025</b>",
  88: "<b>88. REFORMA CONSTITUCIONAL</b> El proyecto de ley declara la necesidad de una reforma parcial de la Constitución de la Ciudad Autónoma de Buenos Aires. Entre las reformas destacadas se incluyen: el fortalecimiento de derechos como propiedad, acceso a la justicia, privacidad y libertad religiosa; una defensa más fuerte contra la ocupación de propiedades privadas; la definición del transporte y la educación como servicios públicos esenciales; y una nueva redacción sobre la seguridad pública que incorpora el derecho a manifestarse pero prohíbe cortes de calles. También se refuerzan los derechos de personas con discapacidad. Presentado el <b>29/04/2025</b> Expediente <b>1303-D-2025</b> ",
  89: "<b>89. PROHIBIR QUE LAS PERSONAS DUERMAN EN LA CALLE</b> El proyecto de ley propone incorporar una nueva contravención al Código Contravencional de la Ciudad de Buenos Aires para permitir al gobierno levantar a personas en situación de calle que, habiendo recibido reiteradamente una oferta habitacional adecuada por parte del Estado, la rechacen sin justificación y permanezcan de forma continua en el espacio público. Presentado el <b>29/04/2025</b> Expediente <b>1304-D-2025</b> ",
  90: "<b>90. ORDENAMIENTO DE FERIAS BARRIALES PARA GARANTIZAR LA LIBRE CIRCULACIÓN VEHICULAR</b> (basta de ferias cortando calles) El proyecto de ley propone prohibir que las Ferias Itinerantes de Abastecimiento Barrial (FIAB) se instalen en calles o avenidas, obligando a que se ubiquen únicamente en plazas, parques u otros espacios públicos designados que no interfieran con la circulación vehicular. El objetivo es garantizar la libre movilidad urbana, facilitar el acceso de servicios de emergencia y reducir las molestias a los vecinos, sin eliminar el funcionamiento de las ferias. Presentado el <b>29/04/2025</b> Expediente <b>1305-D-2025</b>",
  91: "<b>91. SANCIONES POR CARTELES EN ESTADO DE DETERIORO</b> El proyecto de ley busca promover el retiro inmediato de carteles publicitarios en estado de deterioro cuando representen un riesgo o afecten la estética urbana. Busca incentivar su reparación o remoción. Se fundamenta en la necesidad de preservar el paisaje urbano, mejorar la imagen de la Ciudad y evitar que el abandono genere un efecto contagio en el entorno por la dinámica conocida como -Teoría de las ventanas rotas-. Presentado el <b>29/04/2025</b> Expediente <b>1314-D-2025</b>",
  92: "<b>92. ADECUACIÓN DE CONSTRUCCIONES BAJO AUTOPISTA POR RAZONES DE HIGIENE Y SEGURIDAD (evitar puntos ciegos)</b> El proyecto de ley establece que, por razones de higiene y seguridad, las construcciones bajo autopista en la Ciudad de Buenos Aires deberán extenderse hasta la línea oficial, cerrando los espacios abiertos.  El objetivo es evitar el uso indebido de esos espacios, mejorar la salubridad y prevenir actividades ilícitas. Este tipo de lugares suelen ser punto de encuentro de linyeras, dealers y fantasmas. Modificar la estructura urbana ayuda a mejorar la seguridad. Presentado el <b>29/04/2025</b> Expediente <b>1315-D-2025</b>",
  93: "<b>93. EDUCACIÓN FINANCIERA EN COLEGIOS</b> El proyecto de ley propone incorporar de manera obligatoria la educación financiera en todos los niveles y modalidades del sistema educativo de la Ciudad Autónoma de Buenos Aires.  Busca brindar conocimientos teóricos y prácticos sobre el sistema financiero, bancario y crediticio, fomentar el consumo responsable y la toma de decisiones informadas, y preparar a los estudiantes para enfrentar desafíos económicos actuales y futuros. Presentado el <b>30/04/2025</b> Expediente <b>1318-D-2025</b> ",
  94: "<b>94. EXIMIR DEL SISTEMA DE AUTOPROTECCIÓN A ESTABLECIMIENTOS DE HASTA 500 M² DE SUPERFICIE CUBIERTA</b> El proyecto de ley propone eximir del Sistema de Autoprotección a los establecimientos con una superficie cubierta igual o menor a 500 m², al considerar que la normativa actual impone exigencias desproporcionadas para pequeños locales, comercios, espacios culturales y organizaciones sociales que no representan un riesgo significativo. La medida busca aliviar la carga económica y administrativa de estos sectores, manteniendo el espíritu preventivo de la ley y permitiendo que los recursos estatales se enfoquen en establecimientos de mayor complejidad o riesgo. Está chequeado con los que saben,  esto optimiza todo y simplifica la vida de las PYMEs sin aumentar niveles de riesgo. Presentado el <b>30/04/2025</b>  Expediente <b>1321-D-2025</b> ",
  95: "<b>95. SIMPLIFICACIÓN DEL REGISTRO DE PLANOS CONTRA INCENDIO</b> El proyecto de ley propone simplificar el registro de los Planos Conforme a Obra de Instalación contra Incendio, permitiendo que su aprobación y registro estén a cargo de profesionales matriculados sin intervención de la administración pública. Además, exige que la empresa mantenedora del sistema emita una constancia de mantenimiento, y elimina la necesidad de intervención de la Dirección General de Registro de Obras para habilitar el establecimiento, siempre que se cumplan estos requisitos.  El objetivo es agilizar trámites sin comprometer la seguridad, reduciendo la burocracia y facilitando el cumplimiento para los administrados. Presentado el <b>30/04/2025</b> Expediente <b>1323-D-2025</b>",
  96: "<b>96. SANCIONES POR ACARREO INDEBIDO DE VEHÍCULOS</b>  Hace unos años se aprobó una ley de nuestro bloque que disminuye la cantidad de casos en los cuales las grúas están autorizadas a remolcar vehículos. El Gobierno de la CABA hace lo que quiere y levantan autos que, por norma, no deben ser levantados. Lo hablé oportunamente con las autoridades ejecutivas y no les importó, así que ahora propongo sancionar a los funcionarios que desafíen la ley. El proyecto de ley incorpora una sanción para los casos de acarreo indebido de vehículos en la Ciudad de Buenos Aires, estableciendo que cuando un vehículo sea removido sin estar en infracción según el Código de Tránsito, la empresa responsable deberá pagar una multa equivalente al doble de la tasa de acarreo más la estadía acumulada hasta la devolución del vehículo.  La medida busca prevenir abusos, garantizar el respeto al debido proceso y resarcir económicamente a los ciudadanos afectados por remociones arbitrarias. Presentado el <b>30/04/2025</b>  Expediente <b> 1324-D-2025</b>  ",
  97: "<b>97. RESTRICCIÓN DE CARRILES PARA BICICLETAS FRENTE A ACCESOS DE CENTROS DE SALUD</b> El proyecto de ley prohíbe ubicar carriles para bicicletas frente a los ingresos principales o accesos de emergencia de hospitales, clínicas, anexos y centros de rehabilitación en la Ciudad de Buenos Aires, con el objetivo de no obstaculizar la circulación de ambulancias y personal médico. La medida aplicará solo a nuevos carriles que se diseñen o construyan tras la entrada en vigencia de la norma, preservando la infraestructura existente, y busca equilibrar la movilidad sustentable con el acceso seguro a la atención médica. Presentado el <b>30/04/2025</b> Expediente <b>1333-D-2025</b>",
  98: "<b>98. SANCIÓN POR OMISIÓN DE COBROS EN SALUD PÚBLICA</b> El proyecto incorpora una nueva falta al Régimen de Faltas de la Ciudad Autónoma de Buenos Aires para sancionar a los funcionarios públicos que no gestionen el cobro a entidades privadas como prepagas, obras sociales o ART por prestaciones brindadas por hospitales públicos a sus afiliados.  La medida busca garantizar el recupero de fondos que legalmente corresponden al sistema de salud pública, evitando perjuicios económicos al Estado y promoviendo una gestión responsable, eficiente y equitativa de los recursos públicos. Presentado el <b>30/04/2025</b> Expediente <b>1339-D-2025</b>",
  99: "<b>99. MODERNIZACIÓN DEL SISTEMA DE TRANSPORTE PARTICULAR DE PASAJEROS</b> (taxis, Uber, Didis, Cabify y más) El proyecto propone darle un marco regulatorio al transporte entre particulares mediante aplicaciones, al considerar que esta modalidad no se encuadra en las normativas actuales de taxis o remises. Busca saldar un vacío legal con un marco moderno que promueva la competencia, amplíe la oferta laboral y proteja al consumidor, garantizando derechos constitucionales como la libertad de trabajar y elegir cómo viajar. La iniciativa, elaborada con aportes de actores del sector, apunta a una legislación equilibrada y acorde a los principios de innovación, defensa del usuario y regulación de los mercados establecidos por la Constitución de la Ciudad. Más competencia, mejor calidad y mejores precios para los consumidores. Presentado el <b>29/4/2025</b> Expediente <b>1317-D-2025</b> ",
  100: "<b>100. SISTEMA DE REGISTRACIÓN DE BOLETOS DE COMPRAVENTA DE INMUEBLES</b> (fin de las estafas) El proyecto propone la creación de un sistema público y obligatorio de registración de boletos de compraventa de inmuebles en la Ciudad Autónoma de Buenos Aires. Su objetivo es brindar mayor transparencia, seguridad jurídica y protección al consumidor, permitiendo el acceso a la información, evitando fraudes como la venta múltiple del mismo inmueble, mejorando el control y la seguridad sobre estas operaciones. Presentado el <b>30/04/2025</b> Expediente <b>1342-D-2025</b>",
  101: "<b>YAMIL SANTORO</b>",
};

let anguloActual = 0;

function girarRuleta() {
  const ruleta = document.getElementById("ruleta");
  const sonido = document.getElementById("ruletaSonido");

  sonido.currentTime = 0;
  sonido.play();

  const vueltas = Math.floor(Math.random() * 5) + 5;
  const extra = Math.floor(Math.random() * 360);
  const nuevoGiro = vueltas * 360 + extra;
  anguloActual += nuevoGiro;

  ruleta.style.transform = `rotate(${anguloActual}deg)`;

  setTimeout(() => {
    const final = anguloActual % 360;
    const seleccionado = Math.ceil(final / 3.6);
    let numero = 100 - seleccionado + 1;
    if (numero > 100) numero = 1;
    if (numero < 1) numero = 100;

    mostrarProyecto(numero);
  }, 4000);
}

function mostrarProyecto(numero) {
  const texto = proyectos[numero] || "Propuesta no definida.";
  const respuesta = document.getElementById("respuesta");
  respuesta.innerHTML = `
    <h2>100 PROYECTOS DE LEY</h2>
    <div class="propuesta">${texto}</div>
  `;
}
