const proyectos = {
  "1": "Proyecto 1: Descripción del proyecto número 1",
  "2": "Proyecto 2: Descripción del proyecto número 2",
  "3": "Proyecto 3: Descripción del proyecto número 3",
  "4": "Proyecto 4: Descripción del proyecto número 4",
  "5": "Proyecto 5: Descripción del proyecto número 5",
  "6": "Proyecto 6: Descripción del proyecto número 6",
  "7": "Proyecto 7: Descripción del proyecto número 7",
  "8": "Proyecto 8: Descripción del proyecto número 8",
  "9": "Proyecto 9: Descripción del proyecto número 9",
  "10": "Proyecto 10: Descripción del proyecto número 10",
  "11": "Proyecto 11: Descripción del proyecto número 11",
  "12": "Proyecto 12: Descripción del proyecto número 12",
  "13": "Proyecto 13: Descripción del proyecto número 13",
  "14": "Proyecto 14: Descripción del proyecto número 14",
  "15": "Proyecto 15: Descripción del proyecto número 15",
  "16": "Proyecto 16: Descripción del proyecto número 16",
  "17": "Proyecto 17: Descripción del proyecto número 17",
  "18": "Proyecto 18: Descripción del proyecto número 18",
  "19": "Proyecto 19: Descripción del proyecto número 19",
  "20": "Proyecto 20: Descripción del proyecto número 20",
  "21": "Proyecto 21: Descripción del proyecto número 21",
  "22": "Proyecto 22: Descripción del proyecto número 22",
  "23": "Proyecto 23: Descripción del proyecto número 23",
  "24": "Proyecto 24: Descripción del proyecto número 24",
  "25": "Proyecto 25: Descripción del proyecto número 25",
  "26": "Proyecto 26: Descripción del proyecto número 26",
  "27": "Proyecto 27: Descripción del proyecto número 27",
  "28": "Proyecto 28: Descripción del proyecto número 28",
  "29": "Proyecto 29: Descripción del proyecto número 29",
  "30": "Proyecto 30: Descripción del proyecto número 30",
  "31": "Proyecto 31: Descripción del proyecto número 31",
  "32": "Proyecto 32: Descripción del proyecto número 32",
  "33": "Proyecto 33: Descripción del proyecto número 33",
  "34": "Proyecto 34: Descripción del proyecto número 34",
  "35": "Proyecto 35: Descripción del proyecto número 35",
  "36": "Proyecto 36: Descripción del proyecto número 36",
  "37": "Proyecto 37: Descripción del proyecto número 37",
  "38": "Proyecto 38: Descripción del proyecto número 38",
  "39": "Proyecto 39: Descripción del proyecto número 39",
  "40": "Proyecto 40: Descripción del proyecto número 40",
  "41": "Proyecto 41: Descripción del proyecto número 41",
  "42": "Proyecto 42: Descripción del proyecto número 42",
  "43": "Proyecto 43: Descripción del proyecto número 43",
  "44": "Proyecto 44: Descripción del proyecto número 44",
  "45": "Proyecto 45: Descripción del proyecto número 45",
  "46": "Proyecto 46: Descripción del proyecto número 46",
  "47": "Proyecto 47: Descripción del proyecto número 47",
  "48": "Proyecto 48: Descripción del proyecto número 48",
  "49": "Proyecto 49: Descripción del proyecto número 49",
  "50": "Proyecto 50: Descripción del proyecto número 50",
  "51": "Proyecto 51: Descripción del proyecto número 51",
  "52": "Proyecto 52: Descripción del proyecto número 52",
  "53": "Proyecto 53: Descripción del proyecto número 53",
  "54": "Proyecto 54: Descripción del proyecto número 54",
  "55": "Proyecto 55: Descripción del proyecto número 55",
  "56": "Proyecto 56: Descripción del proyecto número 56",
  "57": "Proyecto 57: Descripción del proyecto número 57",
  "58": "Proyecto 58: Descripción del proyecto número 58",
  "59": "Proyecto 59: Descripción del proyecto número 59",
  "60": "Proyecto 60: Descripción del proyecto número 60",
  "61": "Proyecto 61: Descripción del proyecto número 61",
  "62": "Proyecto 62: Descripción del proyecto número 62",
  "63": "Proyecto 63: Descripción del proyecto número 63",
  "64": "Proyecto 64: Descripción del proyecto número 64",
  "65": "Proyecto 65: Descripción del proyecto número 65",
  "66": "Proyecto 66: Descripción del proyecto número 66",
  "67": "Proyecto 67: Descripción del proyecto número 67",
  "68": "Proyecto 68: Descripción del proyecto número 68",
  "69": "Proyecto 69: Descripción del proyecto número 69",
  "70": "Proyecto 70: Descripción del proyecto número 70",
  "71": "Proyecto 71: Descripción del proyecto número 71",
  "72": "Proyecto 72: Descripción del proyecto número 72",
  "73": "Proyecto 73: Descripción del proyecto número 73",
  "74": "Proyecto 74: Descripción del proyecto número 74",
  "75": "Proyecto 75: Descripción del proyecto número 75",
  "76": "Proyecto 76: Descripción del proyecto número 76",
  "77": "Proyecto 77: Descripción del proyecto número 77",
  "78": "Proyecto 78: Descripción del proyecto número 78",
  "79": "Proyecto 79: Descripción del proyecto número 79",
  "80": "Proyecto 80: Descripción del proyecto número 80",
  "81": "Proyecto 81: Descripción del proyecto número 81",
  "82": "Proyecto 82: Descripción del proyecto número 82",
  "83": "Proyecto 83: Descripción del proyecto número 83",
  "84": "Proyecto 84: Descripción del proyecto número 84",
  "85": "Proyecto 85: Descripción del proyecto número 85",
  "86": "Proyecto 86: Descripción del proyecto número 86",
  "87": "Proyecto 87: Descripción del proyecto número 87",
  "88": "Proyecto 88: Descripción del proyecto número 88",
  "89": "Proyecto 89: Descripción del proyecto número 89",
  "90": "Proyecto 90: Descripción del proyecto número 90",
  "91": "Proyecto 91: Descripción del proyecto número 91",
  "92": "Proyecto 92: Descripción del proyecto número 92",
  "93": "Proyecto 93: Descripción del proyecto número 93",
  "94": "Proyecto 94: Descripción del proyecto número 94",
  "95": "Proyecto 95: Descripción del proyecto número 95",
  "96": "Proyecto 96: Descripción del proyecto número 96",
  "97": "Proyecto 97: Descripción del proyecto número 97",
  "98": "Proyecto 98: Descripción del proyecto número 98",
  "99": "Proyecto 99: Descripción del proyecto número 99",
  "100": "Proyecto 100: Descripción del proyecto número 100",
};


const ruleta = document.getElementById("ruleta");
const resultado = document.getElementById("resultado");

function girarRuleta() {
  const grados = 360 * 5 + Math.floor(Math.random() * 360);
  ruleta.style.transform = "rotate(" + grados + "deg)";

  const elegido = 100 - Math.floor((grados % 360) / 3.6);
  const numero = elegido === 0 ? 100 : elegido;

  setTimeout(() => {
    resultado.innerText = proyectos[numero];
  }, 4000);
}
