
const proyectos = {
  1: "<b>PROHIBICIÓN DE TRAPITOS.</b>Ya presentamos un proyecto de ley para convertir en contravención a la actividad de los trapitos/ cuidadoches. Los trapitos: prohibidos y presos. MODIFICASE LA LEY N° 1472, CÓDIGO CONTRAVENCIONAL DE LA CIUDAD* Expediente: <b>3704-D-2024</b> Presentado: <b>6/2/2025</b> ",
  2: "<b>2. TRANSPORTE COMO SERVICIO PÚBLICO ESENCIAL</b> Presenté un proyecto para que el transporte urbano sea declarado como servicio público esencial. ¿Qué quiere decir eso? Que ningún paro o protesta puede impedir que se provea el servicio. Es decir, vas a tener transporte siempre, aunque sea con menor frecuencia. Definir a un servicio público como esencial ayuda a que podamos armonizar de mejor manera los derechos y se logra impedir que haya adhesiones forzosas al paro. Si no se corta al transporte, muchas personas van a ir a trabajar igual si no adhieren al paro. Más libertad, más orden, mejor convivencia. Presentado el <strong>30/10/2024</strong> Expediente <strong>3157-D-2024</strong>  ",
  3: "<b>3. EDUCACIÓN COMO SERVICIO PÚBLICO ESENCIAL</b> Presenté un proyecto para que la educación sea declarada como servicio público esencial. ¿Qué quiere decir eso? Que ningún paro va a impedir que tus hijos estén en la escuela. Muchas veces las medidas de fuerza afectan a la cantidad de días de clase efectivos y eso disminuye el rendimiento escolar de nuestros hijos, condicionando su futuro y el de nuestro país.  Además, cuando un hijo se queda sin ir a clases, muchas veces sus padres tienen que perder el día de trabajo o incurrir en mayores gastos. Por eso presenté este proyecto para evitar que usen a nuestros hijos de rehenes. Presentado el <b>6/3/2025</b> Expediente <b>325-D-2025</b> ",
  4: "<b>4. PROVISIÓN DE COMBUSTIBLE COMO SERVICIO PÚBLICO ESENCIAL</b> Presenté un proyecto para que toda la cadena de suministro de combustible sea declarada un servicio público esencial para que los paros no impidan que puedas cargar combustible. Junto con los dos proyectos anteriores, constituyen un paquete que busca evitar que el paro de actividades que condicionan a todos los trabajadores generen una adhesión forzosa al paro. Con subtes, colectivos, colegios y estaciones de servicio funcionando los días de paro; se lograría evitar bastante que aquellas personas que no quieren parar se vean obligadas a hacerlo a pesar de su decisión.  Presentado el <b>10/4/2025</b> Expediente <strong>1035-D-2025</strong>",
  5: "<b>5. RECOLECCIÓN DE RESIDUOS COMO SERVICIO PÚBLICO ESENCIAL</b> Presenté un proyecto para que que los recolectores de basura no puedan hacer un paro tal que haga que se llene la Ciudad de basura. Hoy la Ciudad amaneció siendo una mugre porque ayer los recolectores de basura decidieron sumarse al paro. Ya ha pasado en otras discusiones que se usa a la basura como una forma de presionar a los gobiernos. Hay que dejarse de joder y poner límites a la protesta. La basura no puede ser un instrumento de extorsión (Recuerden sacar la basura de 19 a 21 y tirarla dentro del tacho). Presentado el <b>11/4/2025</b> Expediente <b>1039-D-2025</b> ",
  6: "<b>6. CREAR LA CALLE -VÍA BIBAS- EN VÍA VIVA</b> Presenté un proyecto para crear una calle peatonal denominada -Vía Bibas-, en homenaje a la familia Bibas - Silberman, donde actualmente funciona el paseo comercial Vía Viva, en el barrio de Belgrano. Actualmente la calle donde funciona el paseo gastronómico ubicado cerca del Barrio Chino, no es reconocida topográficamente como una calle formal en la Ciudad de Buenos Aires. Esto se debe a que es una calle creada hace poco por la elevación de las vías del tren y, por ende, carece todavía de una denominación legal otorgada por la Legislatura. ",
  7: "<b>7.EXENCIÓN DE INGRESOS BRUTOS PARA TODOS LOS GRADUADOS UNIVERSITARIOS Y DE TERCIARIOS.</b> Actualmente los graduados universitarios de carreras de más de 3 años no debemos pagar ingresos brutos en la Ciudad de Buenos Aires. Propongo extender este beneficio a aquellos que se hayan formado tecnicaturas y terciarios a fin de fomentar la profesionalización. Este proyecto se va a tratar MAÑANA en la comisión de presupuesto en la Legislatura Porteña y puede representar un ahorro importante para muchos contribuyentes. Premiando a quienes invierten tiempo estudiando y generando más riqueza para nuestra Ciudad con mejores servicios. Presentado el <b>25/11/24</b> Expediente <b>3394-D-2024</b>  ",
  8: "<b>8. FIRMAS DIGITALES PARA INICIATIVAS POPULARES.</b> El proyecto propone modernizar la Ley N° 40 sobre Iniciativa Popular en la Ciudad de Buenos Aires. Gracias a esta ley, los ciudadanos pueden elaborar y presentar proyectos que deben ser tratados si logran juntar una gran cantidad de firmas. El problema es que actualmente solo se puede hacer con firmas físicas, lo cual favorece al fraude y representa un esfuerzo enorme para los que quieren hacerlo seriamente.  Presentado el <b>5/12/23</b> Expediente <b>2731-D-2023</b> ",
  9: "<b>9. ATENCIÓN MÉDICA PRIORITARIA PARA PORTEÑOS EN HOSPITALES PÚBLICOS.</b> El proyecto establece que los hospitales públicos de la Ciudad de Buenos Aires deben atender con prioridad a las personas con domicilio legal en la ciudad.  El proyecto se fundamenta en la alta demanda de pacientes no porteños —especialmente de la provincia de Buenos Aires— que sobrecarga el sistema de salud local, dificultando el acceso a turnos por parte de quienes vivimos en la Ciudad de Buenos Aires. Presentado el <b>3/4/25</b> Expediente <b>988-D-2025</b>",
  10: "<b>10. RECOBRO A LAS PROVINCIAS DE ORIGEN POR LA ATENCIÓN HOSPITALARIA A ARGENTINOS NO RESIDENTES EN CABA.</b> El proyecto obliga al gobierno de la Ciudad a cobrar a otras provincias por la atención médica brindada a no residentes, incorporando esos ingresos al presupuesto de salud porteño. También faculta al Jefe de Gobierno a firmar acuerdos de reciprocidad sanitaria con otras jurisdicciones. Presentado el 3/4/25 Expediente 988-D-2025",
  11: "<b>11. COBRO DE LA ATENCIÓN MÉDICA EN HOSPITALES PÚBLICOS A EXTRANJEROS NO RESIDENTES.</b> El proyecto de ley busca asegurar el acceso igualitario al sistema de salud pública de la Ciudad de Buenos Aires para personas extranjeras con residencia permanente o temporaria, mientras que establece la obligación de contar con seguro médico o abonar por los servicios para quienes no tengan residencia legal en la Ciudad. En casos de emergencia, se garantiza la atención médica, pero los gastos deberán ser cubiertos por el país de origen. Se propone modificar la legislación vigente para permitir el cobro de estas prestaciones y destinar los fondos recaudados a un fondo de compensación salarial para el personal sanitario. La iniciativa busca evitar abusos al sistema de salud porteño por parte de extranjeros no residentes, promover la reciprocidad con otros países y proteger los recursos públicos y a los contribuyentes locales. Presentado el <b>23/10/24</b> Expediente <b>3095-D-2024</b>",
  12: "<b>12. FICHA LIMPIA.</b> Este proyecto busca crear un sistema de ficha limpia para la Ciudad de Buenos Aires, impidiendo que personas con condena en doble instancia puedan ser candidatos para cargos electivos en la Ciudad de Buenos Aires. Presentado el <b>5/7/24</b>  Expediente <b>1903-D-2024</b>",
  13: "<b>13. LIBRE ELECCIÓN DE MEDIOS DE PAGO EN EL TRANSPORTE PÚBLICO.</b> El proyecto propone que, además de la tarjeta SUBE, los usuarios del transporte público de la Ciudad Autónoma de Buenos Aires puedan abonar sus viajes con tarjetas bancarias sin contacto, billeteras digitales, códigos QR u otros medios electrónicos. Esto incluye al subte, premetro y colectivos que operan exclusivamente en la ciudad. El objetivo es facilitar el acceso, evitar trámites engorrosos y desmonopolizar el sistema de pagos, fomentando la competencia y la comodidad para los usuarios. La autoridad de aplicación será la Secretaría de Transporte, que podrá ampliar medios de pago y coordinar con autoridades nacionales para mantener beneficios vigentes como la Tarifa Social.  Presentado el <b>9/4/24</b>  Expediente <b>0881-D-2024</b>",
  14: "<b>14. ORDENAMIENTO DEL FESTEJO DE LOS CARNAVALES EN LA CIUDAD: BASTA DE CORTES Y SUBSIDIOS.</b> El proyecto de ley propone reorganizar las prácticas y los festejos del Carnaval Porteño para que se realicen en plazas, parques, centros culturales y clubes, evitando el corte de calles. Establece que las prácticas se realicen en espacios con acondicionamiento acústico adecuado para no afectar a los vecinos, y deroga leyes y ordenanzas anteriores que promovían la realización de corsos en la vía pública. Es decir, que se practique y ejecuten donde no molesten. El objetivo es reducir el impacto en el tránsito, el descanso y la seguridad de los ciudadanos, así como optimizar el gasto público —que en 2025 superó los $1.000 millones— destinando los recursos a otras prioridades Presentado el 9/2/24 Expediente <b>2898-D-2023</b>",
  15: "<b>15. FIN DEL SUBSIDIO TOTAL A LA ENERGÍA ELÉCTRICA EN VILLAS Y BARRIOS POPULARES.</b> El proyecto de ley propone terminar con la absurda política de subsidios actual que hace que los porteños paguemos la totalidad del consumo eléctrico de todas las villas y barrios populares de la CABA. Esto lleva a todo tipo de distorsiones, abusos e inequidades. Por tal motivo propongo cortar con el regalo eléctrico y avanzar a una lógica de medidores por hogar, a fin de que cada cual pueda hacerse cargo de sus consumos.  Aquellas familias que requieran una asistencia por alguna cuestión socioeconómica seguirán teniendo el amparo de la tarifa social dispuesta por el Gobierno Nacional. Pero hay que dejar de subsidiar el 100% de todo lo que acontece dentro de los barrios. Presentado el 12/4/25 Expediente <b>1058-D-2025</b>",
  16: "<b>16. CREACIÓN DEL PROGRAMA DE INSPECCIÓN POLIVALENTE.</b> El proyecto propone centralizar la fiscalización comercial en la Ciudad de Buenos Aires mediante un cuerpo único de Inspectores Polivalentes bajo la Agencia Gubernamental de Control, excluyendo los controles tributarios y laborales. Hoy cada local recibe la visita de al menos 6 cuerpos inspectivos distintos, robándole una cantidad innecesaria de horas y representando un gasto público mayor al necesario. Se transfieren y amplían funciones de distintos organismos a esta agencia, incluyendo controles de higiene urbana, publicidad exterior y residuos.  Además, se establece la obligación de notificar con al menos 30 días hábiles de anticipación cualquier inspección (excepto las laborales o tributarias), bajo pena de nulidad.  El objetivo es evitar duplicidad de inspecciones, reducir costos y simplificar el procedimiento para los comerciantes. Presentado el <b>17/1/24</b> Expediente <b>2851-D-2023</b>",
  17: "<b>17. TERMINAR CON LA EXIGENCIA DE CAMPANAS EXTRACTORAS CARÍSIMAS DONDE NO SON NECESARIAS.</b> El proyecto de ley propone modificar el Código de Edificación de la Ciudad de Buenos Aires para actualizar los requisitos técnicos de cocinas y espacios para cocinar, incluyendo dimensiones mínimas, ventilación e iluminación. Se introduce la posibilidad de exceptuar la obligación de instalar campanas extractoras cuando los alimentos solo se calientan y no se cocinan, o en cocinas con escaso uso de fuego. Esta modificación busca reducir costos para pequeños negocios y eventos temporales, y facilitar su instalación sin comprometer las normas de higiene y seguridad alimentaria. Presentado el <b>3/5/24</b> Expediente <b>1190-D-2024</b>",
  18: "<b>18. CORTAR EL MILLONARIO E INEFICIENTE SUBSIDIO A LOS -MEDIOS VECINALES-</b> El proyecto propone derogar la Ley 2587, que desde 2007 establece un régimen de financiamiento publicitario para los medios vecinales de comunicación social de la Ciudad de Buenos Aires. Hoy implica un costo en el orden de los $5.000.000.000 que le aportan poco valor a la ciudadanía. Presentado el <b>22/10/24</b>  Expediente <b>3076-D-2024</b>",
  19: "<b>19. MAYOR SEGURIDAD EN EL SERVICIO DE SUBTERRÁNEOS: SENSORES EN PUERTAS QUE BLOQUEEN EL ARRANQUE  INSEGURO.</b> El proyecto de ley establece la incorporación obligatoria de un sistema de interbloqueo de puertas en todas las formaciones del subte de la Ciudad de Buenos Aires, que impida el inicio de la marcha de la formación si alguna puerta no está completamente cerrada y asegurada. Esta medida busca prevenir accidentes como el ocurrido en marzo de 2025 en la Línea B, donde una mujer resultó gravemente herida ya que la formación arrancó mientras su pierna quedó atrpada en la puerta del subte y como resultado del daño recibido tuvieron que amputarle la pierna. Presentado el <b>7/4/25</b>  Expediente <b>1005-D-2025</b>",
  20: "<b>20. DEVOLUCIÓN DE ABL Y PATENTES POR EL AHORRO DEL COSTO DE LAS PASO.</b> El proyecto de ley propone aplicar una bonificación impositiva de hasta el 100% en el Impuesto Inmobiliario, la Tasa de ABL y Patentes vehiculares a los contribuyentes de la Ciudad de Buenos Aires, utilizando los $20.000.000.000 ahorrados por la suspensión de las elecciones PASO en 2025. Ya que se suspendieron las PASO con la excusa de ahorrarle tiempo y dinero a los contribuyentes, corresponde que ese dinero vuelva a la gente y no quede en manos de los políticos. La medida busca devolver ese ahorro a los vecinos, premiando su aporte al sostenimiento de la Ciudad y promoviendo una gestión eficiente, transparente y orientada al beneficio directo de la ciudadanía.  Presentado el <b>24/2/25</b> Expediente <b>3761-D-2024</b>",
  21: "<b>21. ESTABLECER UN LÍMITE RAZONABLE DE ALCOHOL EN SANGRE PARA ACOMPAÑANTES DE MOTOS.</b> El proyecto de ley modifica el Código de Tránsito de la Ciudad de Buenos Aires para establecer que el acompañante de un motovehículo no podrá circular si supera los 0,5 g/l de alcohol en sangre. Este cambio resulta necesario a partir del surgimiento de nuevos servicios de transporte como UBER y Didi moto. En estos casos, el acompañante deberá descender del vehículo, se le labrará una infracción y no podrá volver a subirse. El conductor no será sancionado si su propio  nivel de alcoholemia es legal. La propuesta busca clarificar responsabilidades, evitar sanciones injustas al conductor y reforzar la seguridad vial mediante la responsabilidad individual. Presentado el <b>2/1/25</b>   Expediente <b>3626-D-2024</b>",
  22: "<b>22. PERMITIR LA LIBRE CIRCULACIÓN DE VEHÍCULOS EN EL CENTRO PORTEÑO.</b> El proyecto de ley propone derogar la Ley N.° 5.786, que estableció el Área Ambiental Buenos Aires Centro, la cual prohibe el acceso en automovil al centro porteño, ya que las condiciones urbanas han cambiado significativamente desde su sanción en 2016. La reducción de la población flotante, el aumento del trabajo remoto y el descenso de la contaminación sin necesidad de restricciones vehiculares han disminuido la efectividad de la norma. Además, se documenta un fuerte impacto económico negativo en el comercio, el empleo y el mercado inmobiliario de la zona. Si es que alguna vez tuvo sentido esta norma, en el presente sus consecuencias son netamente negativas. Presentado el <b>4/12/24</b>   Expediente <b>3497-D-2024</b>",
  23: "<b>23. MODIFÍCASE LA DENOMINACIÓN DE LA ACTUAL CALLE “REPÚBLICA BOLIVARIANA DE VENEZUELA” POR LA DE “REPÚBLICA DE VENEZUELA” </b>",
  24: "<b>24. PROCESO EJECUTIVO DE DESALOJO POR FALTA DE PAGO (DESALOJO EXPRESS I).</b>El proyecto de ley crea un proceso ejecutivo de desalojo por falta de pago en la Ciudad de Buenos Aires, al que las partes podrán adherir de forma optativa al firmar un contrato de alquiler. Este régimen permite que, si el locatario no realiza dos pagos consecutivos del alquiler en una cuenta bancaria especialmente abierta y registrada en el Banco Ciudad, el banco emita una certificación de incumplimiento que funcionará como título ejecutivo, facilitando un desalojo rápido y con escasas posibilidades de defensa. Presentado el <b>4/4/25</b>  Expediente <b>0994-D-2025</b>",
  25: "<b>25. DESALOJO EXPRESS EN 5 DÍAS EN LA CABA Y QUITA DE SUBSIDIOS PARA OKUPAS (DESALOJO EXPRESS II).</b> El proyecto incorpora al Código Contravencional porteño una figura que sanciona con trabajo comunitario, multa y la inhabilitación para recibir subsidios a quienes ocupen inmuebles sin poder acreditar la legalidad de su ocupación demás, si el propietario o tenedor legal denuncia la situación, el juez podrá ordenar el desalojo inmediato si el ocupante no justifica documentalmente su derecho en un plazo de cinco días. Con esta medida vamos a lograr aumentar la oferta de propiedades en alquiler de la Ciudad de Buenos Aires logrando así que se baje el precio de los alquileres. Presentado el <b>4/4/25</b>  Expediente <b>0993-D-2025</b>",
  26: "<b>26. BENEFICIOS FISCALES POR CONTRATAR TRABAJADORES CON DISCAPACIDAD.</b> El proyecto de ley propone modificar el artículo 243 del Código Fiscal para ampliar los beneficios fiscales a empleadores que contraten personas con discapacidad. Presentado el <b>6/1/25</b>  Expediente <b>1136-D-2025</b>",
  27: "<b>27. BENEFICIOS FISCALES POR CONTRATAR VETERANOS DE LA GUERRA DE LAS ISLAS MALVINAS.</b> El proyecto de ley propone incorporar un beneficio fiscal en el Código Fiscal de la Ciudad de Buenos Aires para incentivar la contratación de ex combatientes héroes de la Guerra de Malvinas, Georgias, Sándwich e Islas del Atlántico Sur. Los empleadores que contraten a estos veteranos podrán deducir el 100% de las contribuciones patronales abonadas del Impuesto sobre los Ingresos Brutos. La medida busca reparar una deuda histórica con quienes defendieron la soberanía nacional y enfrentan dificultades económicas, sociales y laborales, reconociendo su valor mediante inclusión laboral y alivio fiscal para las empresas que los empleen. También se permitirá aplicar el beneficio a veteranos ya contratados al momento de la entrada en vigencia de la norma.  Presentado el <b>21/04/2025</b> Expediente <b>1137-D-2025</b>",
  28: "<b>28. BENEFICIOS FISCALES POR CONTRATAR A PERSONAS MAYORES.</b> El proyecto de ley propone incorporar un beneficio fiscal en el Código Fiscal de la Ciudad Autónoma de Buenos Aires para incentivar la contratación y retención de personas mayores. Establece que los contribuyentes que desarrollen actividades productivas, comerciales o de servicios podrán deducir entre el 50% y el 100% de las contribuciones patronales abonadas por trabajadores mayores, conforme a la Ley 6753 y otras normativas nacionales. Esta medida busca fomentar la inclusión laboral de personas mayores, combatir la discriminación por edad y reconocer su aporte a la sociedad, al tiempo que ofrece un alivio impositivo a los empleadores. También contempla una cláusula transitoria para que el beneficio alcance a quienes ya tengan personas mayores empleadas. Presentado el <b>21/04/2025</b> Expediente <b>1138-D-2025</b>",
  29: "<b>29. ELIMINACIÓN DEL NOMBRE DE RODOLFO WALSH EN ESPACIOS PÚBLICOS DE LA CIUDAD.</b> Presenté cinco proyectos de ley para sustituir el nombre de Rodolfo Walsh en distintos espacios públicos de la Ciudad Autónoma de Buenos Aires, en virtud de un fallo judicial que lo vincula con la planificación del atentado del 2 de julio de 1976 en la Superintendencia de Seguridad Federal, que causó 23 muertes y más de 100 heridos, y cuya responsabilidad torna éticamente inadmisible su homenaje en el ámbito público. Presentado el <b>20/12/2024</b>  Expediente <b>3600-D-2024</b> Presentado el <b>21/11/2024</b> Expediente <b>3396-D-2024</b>",
  30: "<b>30. QUE LOS PRESOS SE HAGAN CARGO DEL COSTO DE SU DETENCIÓN</b> El proyecto de ley crea un Sistema de Reintegro de Gastos para que las personas privadas de su libertad en la Ciudad Autónoma de Buenos Aires, una vez condenadas, afronten los costos de su detención, estimados en $27.000 diarios por persona. En caso de no poder abonarlos, deberán realizar trabajos en los establecimientos como forma de compensación, siempre bajo condiciones que respeten la dignidad humana y la proporcionalidad de esfuerzos. Presentado el <b>19/12/2024</b>  Expediente <b>3596-D-2024</b>",
  31: "<b>31. REDUCCIÓN DEL NÚMERO DE DEFENSORES DEL PUEBLO ADJUNTOS.</b> El proyecto propone reducir de cinco a uno el número de Defensores del Pueblo Adjuntos en la Ciudad Autónoma de Buenos Aires,  con el fin de adecuarla a principios de austeridad ante la crisis económica actual. Además, se elimina la exigencia de paridad de género entre los designados. La iniciativa busca optimizar recursos y fortalecer la confianza ciudadana en las instituciones. Menos cargos políticos, menos gasto público, menos impuestos.",
  32: "<b>32. REDUCCIÓN DEL NÚMERO DE COMUNEROS QUE COBRAN DE 7 A 1.</b> El proyecto de ley propone que solo el presidente de cada Junta Comunal, hay 15 comunas, reciba una remuneración equivalente al 70% del ingreso bruto de un diputado de la Ciudad (aprox 3.5 millones de pesos), mientras que el resto de los miembros desempeñarán sus funciones ad honorem a partir del próximo mandato. Presentado el <b>19/11/2024</b>  Expediente <b>3347-D-2024</b>",
  33: "<b>33. REGLAMENTAR LA LEY DE MECENAZGO CIENTÍFICO. ESTA ES UNA LEY SANCIONADA YA, DE MI AUTORÍA.</b> Crea un régimen de promoción fiscal que incentive a las empresas a financiar proyectos de investigación científica, tecnológica e innovación en áreas estratégicas, con el objetivo de impulsar el desarrollo productivo, industrial y comercial, mejorar la calidad de vida de la población y fortalecer el vínculo entre el sector público, privado y académico. Gracias a esto, los contribuyentes podrán destinar parte del dinero que pagan en concepto de impuestos a financiar proyectos de ciencia, tecnología e innovación. Pero para que la ley entre en vigencia falta que el Poder Ejecutivo la reglamente. Presentado el <b>10/4/2024</b> Expediente <b>0907-D-2024</b>",
  34: "<b>34. EXIGIR QUE EL JEFE DE GOBIERNO, LOS LEGISLADORES Y LOS COMUNEROS TENGAN SECUNDARIO COMPLETO (Ley Zaracho).</b> Hoy te piden tener título secundario para poder acceder a casi cualquier trabajo en el Gobierno de la Ciudad. Sin embargo, por una omisión legal, no resulta requisito para poder ocupar cargos electivos en la Ciudad de Buenos Aires. El fundamento principal es elevar la calidad democrática asegurando que los representantes cuenten con una formación mínima acorde con la creciente complejidad de los desafíos públicos. Presentado el <b>6/3/2024</b> Expediente <b>0549-D-2024</b>",
  35: "<b>35. LIBRE INGRESO DE ANIMALES DOMÉSTICOS DE COMPAÑÍA EN COMERCIOS</b> (si el dueño del local quiere). Hasta ahora estaba prohibido, por ley, entrar con mascotas a una serie de comercios de la CABA. Nuestro proyecto busca levantar esta prohibición y darle la opción a los locales de dejar, o no, acceder a mascotas. La iniciativa busca fomentar una convivencia más inclusiva y alineada con los cambios culturales en torno al bienestar animal. Presentado el <b>24/04/2025</b>  Expediente <b>1172-D-2025</b>",
  36: "<b>36. POSIBILITAR INGRESO DE ANIMALES DOMÉSTICOS DE COMPAÑÍA EN DEPENDENCIAS DEL GOBIERNO DE LA CIUDAD.</b> El proyecto de ley modifica la normativa vigente para permitir el ingreso transitorio de animales domésticos en dependencias del Gobierno de la Ciudad Autónoma de Buenos Aires, salvo cuando exista una prohibición expresa fundada en razones de salubridad, seguridad o funcionamiento específico del área. Así voy a poder recibir a vecinos con sus mascotas en la Legislatura (eso si, traigan bolsitas y toallitas para hacerse cargo de cualquier accidente). Presentado el <b>24/04/2025</b>  Expediente <b>1172-D-2025</b>",
  37: "<b>37. POSIBILITAR EL TRASLADO DE MASCOTAS EN TRANSPORTE PÚBLICO.</b> El proyecto de ley busca permitir que las personas puedan viajar con sus mascotas en el transporte público cumpliendo con medidas básicas de seguridad e higiene cualquier día y en cualquier momento. Actualmente, sólo podés viajar con mascotas los días feriados y domingos durante todo el día, y los sábados después de las 13 :00 horas, podés viajar con tu mascota en el subte. Presentado el <b>24/04/2025</b>   Expediente <b>1207-D-2025</b>",
  38: "<b>38. BENEFICIOS FISCALES PARA REFUGIOS DE ANIMALES.</b> Se busca modificar la norma que establece las exenciones impositivas en la Ciudad de Buenos Aires para que no solo contemple a las -Sociedades protectoras de animales- sino también a las simples asociaciones que funcionen como refugios. Así evitamos que tengan que destinar dinero al pago de impuestos y pueden enfocarse de mejor manera a asistir a los animales en tránsito. Presentado el <b>24/04/2025</b>   Expediente <b>1186-D-2025</b>",
  39: "<b>39. SANCIONES PARA QUIENES NO LEVANTEN LA CACA DE SUS MASCOTAS.</b> El proyecto busca mejorar la convivencia responsabilizando a quienes optan por dejar caca en la viva pública. Amamos a las mascotas pero conllevan responsabilidades. No solo el deber de tratarlas bien y cuidarlas sino también de evitar que perjudiquen a terceros. Con esta ley cada uno se hace cargo de sus cacas. Presentado el <b>24/04/2025</b>  Expediente <b>1208-D-2025</b>",
  40: "<b>40. LEY ANTI-TOMA DE COLEGIOS.</b> El proyecto busca impedir que se tomen Escuelas, facultado a las fuerzas de seguridad a desalojar a quienes busquen llevar adelante medidas de fuerza qué impidan el normal desenvolvimiento de las clases. Presentado el <b>24/04/2025</b>  Expediente <b>1212-D-2025</b>",
  41: "<b>41. ELIMINACIÓN DEL IMPUESTO SOBRE SERVICIOS DIGITALES.</b> El proyecto de ley propone eliminar el impuesto del 2% que actualmente se aplica a todos los servicios digitales prestados desde el exterior, como plataformas de streaming, software, servicios educativos o de almacenamiento en la nube, con excepción de aquellos vinculados a juegos de azar, apuestas y actividades lúdicas equivalentes, que seguirán gravados. La medida busca aliviar la carga sobre los usuarios domiciliados en la Ciudad de Buenos Aires, ya que hoy son quienes terminan asumiendo el costo, y fomentar el acceso a herramientas digitales esenciales para el trabajo, la educación y la producción. Se mantiene el impuesto únicamente para las apuestas digitales debido a su carácter no esencial, su finalidad lucrativa y sus posibles efectos sociales. Presentado el <b>21/04/2025</b> Expediente <b>1127-D-2025</b> ",
  42: "<b>42. DÍA DEL BARMAN CLÁSICO ARGENTINO.</b> El proyecto de ley propone instituir el 3 de abril como -Día del Barman Clásico Argentino- en la Ciudad de Buenos Aires en homenaje a Ariel Lombán, reconocido referente de la coctelería nacional fallecido en 2024. Lombán fue presidente de la Asociación Mutual de Barmen y Afines, impulsó la profesionalización del oficio, rescató recetas tradicionales y promovió ingredientes típicos de la coctelería argentina. La iniciativa busca honrar su legado, preservar el patrimonio cultural de la barra y motivar a nuevas generaciones de bartenders a ejercer con pasión, técnica y respeto por la historia. Presentado el 4/04/2025 Expediente 1003-D-2025",
  43: "<b>43. ORDENAMIENTO DEL SERVICIO PÚBLICO DE HIGIENE URBANA:</b> El proyecto de ley busca reorganizar el Servicio Público de Higiene Urbana de la Ciudad de Buenos Aires, prohibiendo la recolección y comercialización informal de residuos domiciliarios en la vía pública, -carnoteo-, con sanciones como decomisos, multas y arresto. Presentado el <b>1/04/2025</b> Expediente <b>0981-D-2025</b>",
  44: "<b>44. DECLÁRASE CIUDADANO ILUSTRE AL DOCTOR CARLOS SALVADOR BILARDO.</b> El proyecto propone declarar Ciudadano Ilustre de la Ciudad Autónoma de Buenos Aires al Dr. Carlos Salvador Bilardo, en reconocimiento a su destacada trayectoria como futbolista, director técnico y médico. Presentado el <b>31/03/2025</b> Expediente <b>0967-D-2025</b>",
  45: "<b>45. DERÓGASE LA LEY N° 1322 -FERIADOS DE CARNAVAL-</b> El proyecto propone derogar la Ley N.º 1.322, que establece los feriados de Carnaval en la Ciudad de Buenos Aires, argumentando razones económicas, fiscales y de productividad. Se sostiene que estos días no laborables afectan negativamente la actividad comercial y productiva, especialmente en sectores que no se benefician del turismo, y generan un gasto público difícil de justificar en el contexto de crisis económica. La iniciativa aclara que no busca prohibir los festejos, sino eliminar la obligatoriedad de los feriados para permitir su celebración sin afectar la actividad económica. Presentado el <b>25/03/2025</b> Expediente <b>0900-D-2025</b> ",
  46: "<b>46. REGULACIÓN DE LA VENTA Y CONSUMO DE BEBIDAS ALCOHÓLICAS Y FORTALECIMIENTO DE LA SEGURIDAD EN ESTADIOS DE FÚTBOL</b> El proyecto de ley busca permitir la venta y consumo moderado de bebidas alcohólicas en áreas específicas de los estadios de fútbol de la Ciudad de Buenos Aires, bajo estrictas condiciones de seguridad y control. Presentado el <strong>26/02/2025</strong> Expediente <strong> 3766-D-2024</strong>  ",
  47: "<b>47. REGULACIÓN Y SEGURIDAD PARA LA PRESENCIA DE PÚBLICO VISITANTE EN ESTADIOS DE FÚTBOL</b> El proyecto de ley habilita la presencia de público visitante en los estadios de fútbol de la Ciudad de Buenos Aires, bajo estrictas medidas de seguridad, separación física y accesos diferenciados. Establece que el club local será responsable de financiar y coordinar el operativo de seguridad, con posibilidad de aporte del club visitante. Presentado el </strong> 26/02/2025</strong> Expediente <strong> 3765-D-2024</strong>   ",
  48: "<b>48. DECLÁRASE CIUDADANO ILUSTRE AL DR. LUIS OVSEJEVICH</b> El proyecto de ley propone declarar Ciudadano Ilustre de la Ciudad Autónoma de Buenos Aires al Dr. Luis Ovsejevich, en reconocimiento a su destacada trayectoria como abogado, profesor de piano y referente cultural. Presentado el <strong>12/12/2024</strong> Expediente <strong> 3577-D-2024 </strong> ",
  49: "<b>49. DERÓGASE LA ORDENANZA N° 44370<b> El proyecto de ley propone derogar la Ordenanza N° 44370, que otorga un subsidio mensual y vitalicio, argumentando que esta medida ya no se justifica en el contexto actual debido al fortalecimiento del sistema de seguridad social. Presentado el <strong>21/11/2024</strong> Expediente <strong>3395-D-2024</strong>",
  50: "<b>50. MODIFÍCASE LA LEY 6.099.</b> El proyecto de ley incorpora al Código Urbanístico de la Ciudad de Buenos Aires la definición de “Casa Club” como un espacio comunitario no sanatorial destinado a la integración y rehabilitación psicosocial de personas con trastornos mentales, promoviendo su participación activa y autonomía. Presentado el <strong>14/11/2024</strong> Expediente <strong> 3321-D-2024</strong>",
  51: "<b>51.DERÓGASE LA LEY 6.272.</b> El proyecto de ley propone derogar la Ley 6272, que instauró el 29 de octubre como el “Día de la Promoción de los Derechos de las Infancias y Adolescencias Trans”, y obligaba al Estado a implementar campañas de visibilización, capacitaciones y políticas públicas específicas sobre el tema. Presentado el  <strong> 29/10/2024  </strong>   Expediente <strong> 3153-D-2024 </strong>",
  52: "<b>52.MODIFÍCASE LA LEY 578.</b> Esta iniciativa busca establecer límites a las declaraciones y conmemoraciones otorgadas por la Legislatura porteña, con el fin de ordenar y jerarquizar sus actos. Se destaca como antecedente el Decreto N° 5.444/79, que limitaba celebraciones institucionales, promoviendo austeridad. Presentado el <strong>23/10/2024  </strong> Expediente <strong> 3107-D-2024</strong> ",
  53: "<b>53.ESTABLECESE AL PLÁTANO DE SOMBRA (PLATANUS ACERIFOLIA) COMO ESPECIE NO APTA PARA LA CIUDAD.</b> El proyecto de ley propone declarar al Plátano de Sombra (Platanus Acerifolia) como especie no apta para la Ciudad de Buenos Aires, prohibiendo su plantación y estableciendo su reemplazo por especies nativas de bajo impacto alergénico en caso de remoción. Presentado el <strong>3/10/2024</strong> Expediente <strong> 2906-D-2024</strong> ",
  54: "<b>54.MODIFÍCANSE LOS ART. 181 Y OTROS DE LA LEY N° 2303 (T.C. LEY N°6.588) - REITERANCIA DELICTIVA</b> El proyecto modifica el Código Procesal Penal de CABA para permitir la detención preventiva de personas imputadas por reiteración delictiva, sumando esta causal a las ya existentes (riesgo de fuga y entorpecimiento del proceso). Presentado el <strong>22/03/2024 </strong> Expediente <strong> 0751-D-2024</strong> ",
  55: "<b>55.DERÓGANSE LA LEY N° 3517 -CONVENIO MARCO DE COOPERACIÓN SUSCRIPTO CON LA CIUDAD DE SAN PETERSBURGO - Y LA ORDENANZA N° 44536 –HERMANAMIENTO CON LA CIUDAD DE MOSCÚ-</b> El proyecto propone derogar la Ley N° 3517 y la Ordenanza N° 44536, que establecían vínculos institucionales con las ciudades rusas de San Petersburgo y Moscú, en rechazo a la invasión de Ucrania por parte del gobierno de la Federación de Rusia. Presentado el  <strong>11/12/2023</strong> Expediente <strong>2774-D-2023</strong>  ",
  56: "<b>56.REGULACIÓN DE LOS MANDATARIOS DEL GOBIERNO</b> Proyecto de Ley: Regulación de los Mandatarios Judiciales del GCBA El proyecto propone incorporar nuevas disposiciones en la Ley 5.134, el Código Fiscal y la Ley Tarifaria para regular la actuación de los mandatarios judiciales que intervienen en ejecuciones fiscales por deudas tributarias en la Ciudad Autónoma de Buenos Aires. Presentado el <strong>6/03/2024 </strong> Expediente <strong>0533-D-2024</strong>   ",
  57: "<b>57. DENOMÍNASE “ENFERMERAS ARGENTINAS” A LA PLAZOLETA SITA ENTRE LAS CALLES JUANA MANSO Y ROSARIO VERA PEÑALOZA, PUERTO MADERO.</b> Proyecto de Ley: Denominación de la Plazoleta -Enfermeras Argentinas- Se propone nombrar “Enfermeras Argentinas” a la plazoleta ubicada entre Juana Manso y Rosario Vera Peñaloza, en Puerto Madero (Comuna 1) Presentado el <strong>29/10/2024 </strong> Expediente <strong>3144-D-2024</strong>", 
  58: "<b>58.DECLÁRASE CIUDADANA ILUSTRE A LA BANDONEONISTA SEÑORA CARLA ALGERI</b> Proyecto de Ley: Ciudadana Ilustre – Carla Algeri Se propone declarar Ciudadana Ilustre de la Ciudad Autónoma de Buenos Aires a Carla Algeri, bandoneonista, compositora y arregladora, por su destacada trayectoria artística y su aporte a la cultura porteña.  Presentado el <strong>20/09/2024 </strong> Expediente <strong>2755-D-2024</strong> ",
  59: "<b>59. DENOMÍNASE “ESCUELA SUPERIOR DE ENFERMERÍA DOCTORA CECILIA GRIERSON” A LA PLAZOLETA SIN DENOMINACIÓN SITA ENTRE LAS CALLES JUANA MANSO Y ROSARIO VERA PEÑALOZA</b> Proyecto de Ley: Denominación de plazoleta – “Escuela Superior de Enfermería doctora Cecilia Grierson” Se propone denominar “Escuela Superior de Enfermería doctora Cecilia Grierson” a la plazoleta ubicada entre Juana Manso y Rosario Vera Peñaloza, en Puerto Madero (Comuna 1), actualmente sin nombre. Presentado el <strong>9/09/2024 </strong> Expediente <strong>2603-D-2024</strong> ",
  60: "<b>60. DENOMÍNASE “PRESIDENTE DOCTOR ARTURO FRONDIZI” A PLAZOLETA UBICADA EN LA COMUNA 10<7b> Proyecto de Ley: Denominación de plazoleta – “Presidente doctor Arturo Frondizi”Se propone denominar “Presidente doctor Arturo Frondizi” a la plazoleta ubicada entre las calles C. Irigoyen, Bacacay, Ruiz de los Llanos y César Díaz, en Villa Luro (Comuna 10), actualmente sin nombre. Presentado el <strong>28/08/2024</strong> Expediente <strong>2479-D-2024</strong>", 
  61: "<b>61. CONDICIONES PARA LA APLICACIÓN DE SANCIONES PENALES EFECTIVAS CONTRA LOS DELITOS COMETIDOS POR LOS DENOMINADOS “CUIDACOCHES” O “TRAPITOS”</b> El proyecto establece un régimen específico para la denuncia y persecución penal de conductas extorsivas ejercidas por personas que exigen o sugieren el pago de dinero a cambio de “cuidar” vehículos estacionados en la vía pública. Presentado el <strong>8/08/2024</strong> Expediente <strong>2249-D-2024</strong> ",
  62: "<b>62. CREACIÓN DEL REGISTRO GRATUITO DE VOLUNTADES ANTICIPADAS PARA PERSONAS MAYORES.</b> Proyecto de Ley: Este proyecto propone la creación de un registro gratuito en la Ciudad de Buenos Aires para que las personas mayores de 60 años puedan dejar constancia por escrito de sus directivas anticipadas de salud y de exequias. Presentado el <strong>18/07/2024</strong> Expediente <strong>2034-D-2024</strong> ", 
  63: "<b>63. MODIFICACIÓN DE LA LEY 4.803.</b> El proyecto de ley propone modificar la Ley N° 4803 para reducir la frecuencia de las capacitaciones de seguridad e higiene en consorcios de propiedad horizontal, extendiendo su realización de cada 2 años a cada 5 años. Presentado el <b>18/07/2024</b> Expediente <b> 2033-D-2024</b>",
  64: "<b>64.CRÉASE LA PLATAFORMA DIGITAL DENOMINADA “VOTA INFORMADO”</b> Se propone la creación de la plataforma digital -Vota Informado-, gestionada por el Instituto de Gestión Electoral de la Ciudad de Buenos Aires. Su objetivo es brindar información precisa y actualizada sobre los precandidatos y candidatos a cargos electivos en la ciudad, incluyendo sus datos personales, antecedentes laborales y académicos, y propuestas. Presentado el <strong>2/05/2024</strong> Expediente <strong>1175-D-2024 </strong> ",
  65: "<b>65. MODIFÍCASE EL ART. 4 DE LA LEY Nº 6.031 DEL CÓDIGO ELECTORAL DE LA CIUDAD CON EL OBJETO DE IMPLEMENTAR EL SISTEMA DE BOLETA ÚNICA DE PAPEL COMO ÚNICO SISTEMA DE VOTACIÓN.</b> El proyecto de ley propone modificar el Código Electoral de la Ciudad Autónoma de Buenos Aires para establecer la Boleta Única de Papel como único instrumento de votación en elecciones locales, reemplazando la boleta electrónica. Presentado el <strong>7/03/2024</strong> Expediente <strong>0571-D-2024</strong>",
  66: "<b>66. INSTITUYASE EL 22 DE FEBRERO DE CADA AÑO COMO -DIA DE LA LUCHA CONTRA LA CORRUPCION Y POR LA TRANSPARENCIA EN LA CIUDAD- Este proyecto de ley propone instituir el 22 de febrero como el -Día de lucha contra la corrupción y por la transparencia en la Ciudad Autónoma de Buenos Aires-, en memoria de la tragedia ferroviaria de Once de 2012, que expuso un esquema de corrupción en el transporte y provocó la muerte de 52 personas. Presentado el <strong>22/02/2024</strong>  Expediente <strong>2930-D-2023</strong>",
  67: "<b>67. DISCRIMINACIÓN DE IMPUESTOS, TASAS Y CONTRIBUCIONES VIGENTES EN LA CABA EN TODOS LOS COMPROBANTES FISCALES DE CONSUMIDORES FINALES</b> Este proyecto de ley establece que los comprobantes fiscales destinados a consumidores finales en la Ciudad Autónoma de Buenos Aires deben detallar la discriminación de los impuestos, tasas y contribuciones vigentes al momento de su emisión. Presentado el <strong>27/08/2024</strong> Expediente <strong>2472-D-2024</strong>",
  68: "<b>68. DECLÁRASE EN EL ÁMBITO DE LA CIUDAD AUTÓNOMA DE BUENOS AIRES, EL AÑO 2024 COMO EL -AÑO DEL 30° ANIVERSARIO DE LA AUTONOMÍA DE LA CIUDAD DE BUENOS AIRES-.</b> Este proyecto de ley propone declarar el año 2024 como el -Año del 30° Aniversario de la autonomía de la Ciudad de Buenos Aires-. Establece que los papeles oficiales de la ciudad deben incluir la inscripción “2024 - Año del 30° Aniversario de la autonomía de la Ciudad de Buenos Aires”. Presentado el <strong> 15/02/2024</strong> Expediente <strong>2913-D-2023</strong>  ",
  69: "<b>69. DECLÁRASE EL 2 DE JULIO DÍA DE LAS VÍCTIMAS DEL TERRORISMO GUERRILLERO.</b> Se declara el 2 de julio como el Día de las Víctimas del Terrorismo Guerrillero en la Ciudad Autónoma de Buenos Aires, incorporando esta fecha al calendario oficial de la ciudad. Este día recuerda el atentado perpetrado por Montoneros el 2 de julio de 1976 en el Comedor de la Superintendencia de Seguridad Federal, donde murieron 23 personas, incluidos 22 policías y una civil, víctimas de una bomba de gran poder destructivo. Presentado el <strong> 2/07/2024 </strong> Expediente <strong>1856-D-2024 </strong> ",
  70: "<b>70.RETIRO DE CICLOVÍAS MENOS UTILIZADAS.</b> El proyecto de ley dispone el retiro de las ciclovías con una frecuencia menor al 5 % de cruces diarios respecto de la ciclovía más utilizada. Prohíbe la instalación y el retiro de ciclovías sin autorización previa, formal y expresa de la comuna correspondiente, con participación de la Junta Comunal, el Consejo Consultivo Comunal y audiencia de vecinos. Presentado el <strong>15/03/2024</strong> Expediente <strong>0672-D-2024</strong>",
  71: "<b>71.MODIFICASE EL ARTÍCULO 94, CAPÍTULO II “USO DEL ESPACIO PÚBLICO Y PRIVADO”, TÍTULO III “PROTECCIÓN DEL USO DEL ESPACIO PÚBLICO O PRIVADO”, LIBRO II, DEL ANEXO A LEY P – Nº 1.472, CÓDIGO CONTRAVENCIONAL </b> Se modifica el artículo 94 del Código Contravencional de la Ciudad Autónoma de Buenos Aires (Ley Nº 1.472), que regula el uso del espacio público y privado, estableciendo sanciones para quienes manchen o ensucien bienes públicos o privados. Presentado el <strong>15/03/2024</strong> Expediente <strong>0670-D-2024</strong>",
  72: "<b>72.DERÓGANSE LAS LEYES 6.314 Y 5.526.-</b> El proyecto de ley deroga la Ley N.º 6.314 y la Ley N.º 5.526, así como todas las disposiciones del Código de Tránsito y del Régimen de Faltas de la Ciudad vinculadas al servicio de mensajería urbana y reparto a domicilio. Presentado el <strong>15/03/2024</strong> Expediente <strong>0669-D-2024</strong> ",
  73: "<b>73.DERÓGASE LA LEY 3.708 Y MODIFÍCASE LA LEY 451.-</b> El proyecto de ley propone la derogación de la Ley Nº 3.708, que establece el grabado obligatorio de autopartes y el registro de desarmaderos de automóviles, quedando sin efecto el Registro de Verificación de Autopartes creado en el ámbito del Ministerio de Justicia y Seguridad del Poder Ejecutivo. Presentado el <strong>15/03/2024</strong> Expediente <strong>0668-D-2024</strong> ",
  74: "<b>74. ELIMÍNASE LA DENOMINACIÓN “RODOLFO WALSH” DE LA ESTACIÓN DE SUBTERRÁNEOS DE LA LÍNEA E.</b> Este proyecto de ley propone eliminar la denominación -Rodolfo Walsh- de la estación de subterráneos de la línea E en la Ciudad Autónoma de Buenos Aires y mantener como único nombre la estación -Entre Ríos-. Presentado el <strong>15/03/2024</strong> Expediente <strong>0667-D-2024</strong> ",
  75: "<b>75.DECLÁRASE EL AÑO 2024 COMO EL “AÑO DE LA DEFENSA DE LA VIDA, LA LIBERTAD Y LA PROPIEDAD PRIVADA”.</b> El proyecto de ley declara 2024 como el Año de la Defensa de la Vida, la Libertad y la Propiedad Privada-, estableciendo que toda la documentación oficial de la Ciudad lleve esa leyenda. Presentado el <strong>1/03/2024</strong> Expediente <strong>0359-D-2024</strong>  ",
  76: "<b>76.LEY DE CANILES DE LA CIUDAD</b> El proyecto de Ley de Caniles de la Ciudad Autónoma de Buenos Aires busca regular la instalación, diseño, construcción y funcionamiento de caniles en espacios verdes públicos, garantizando espacios seguros, salubres y adecuados para la recreación de perros. Presentado el <strong>22/08/2024</strong>  Expediente <strong>2429-D-2024</strong>  ",
  77: "<b>77.MODIFICASE LA LEY N° 2148 -CÓDIGO DE TRÁNSITO Y TRANSPORTE</b> En 2022, la Ley N.º 6586 limitó el uso de grúas en la Ciudad de Buenos Aires a casos indispensables para la seguridad vial, reduciendo así las remociones, los costos y promoviendo un uso racional de los recursos públicos. Presentado el </strong>10/12/2024</strong> Expediente <strong>3559-D-2024</strong>  ",
  78: "<b>78.",
  79: "<b>79. ",
  80: "<b>80. ",
  81: "<b>81. ",
  82: "<b>82. ",
  83: "<b>83. ",
  84: "<b>84. ",
  85: "<b>85. ",
  86: "<b>86. ",
  87: "<b>87. ",
  88: "<b>88. ",
  89: "<b>89. ",
  90: "<b>90. ",
  91: "<b>91. ",
  92: "<b>92. ",
  93: "<b>93. ",
  94: "<b>94. ",
  95: "<b>95. ",
  96: "<b>96. ",
  97: "<b>97. ",
  98: "<b>98. ",
  99: "<b>99. ",
  100: "<b>100.",
  101: "<b>YAMIL SANTORO</b>",
};

let anguloActual = 0;

function girarRuleta() {
  const ruleta = document.getElementById("ruleta");
  const sonido = document.getElementById("ruletaSonido");

  sonido.currentTime = 0;
  sonido.play();

  const vueltas = Math.floor(Math.random() * 5) + 5;
  const extra = Math.floor(Math.random() * 360);
  const nuevoGiro = vueltas * 360 + extra;
  anguloActual += nuevoGiro;

  ruleta.style.transform = `rotate(${anguloActual}deg)`;

  setTimeout(() => {
    const final = anguloActual % 360;
    const seleccionado = Math.ceil(final / 3.6);
    let numero = 100 - seleccionado + 1;
    if (numero > 100) numero = 1;
    if (numero < 1) numero = 100;

    mostrarProyecto(numero);
  }, 4000);
}

function mostrarProyecto(numero) {
  const texto = proyectos[numero] || "Propuesta no definida.";
  const respuesta = document.getElementById("respuesta");
  respuesta.innerHTML = `
    <h2>100 PROYECTOS DE LEY</h2>
    <div class="propuesta">${texto}</div>
  `;
}
